-- Pneumologia — Prova 3 — 14 questões originalmente fechadas.
-- Idempotente: IDs determinísticos e ON CONFLICT atualiza o conteúdo.
BEGIN;

CREATE OR REPLACE FUNCTION pg_temp.p3_uuid(seed text) RETURNS uuid
LANGUAGE sql IMMUTABLE AS $$
  SELECT (substr(md5(seed),1,8)||'-'||substr(md5(seed),9,4)||'-5'||substr(md5(seed),14,3)||'-a'||substr(md5(seed),18,3)||'-'||substr(md5(seed),21,12))::uuid
$$;

DO $$
DECLARE
  d_id uuid;
  r record;
  q_id uuid;
  t_id uuid;
  a jsonb;
BEGIN
  SELECT id INTO d_id FROM public.disciplines WHERE lower(name)=lower('Pneumologia') LIMIT 1;
  IF d_id IS NULL THEN RAISE EXCEPTION 'Disciplina Pneumologia não encontrada'; END IF;

  FOR r IN SELECT * FROM jsonb_to_recordset($data$[
    {"n":1,"topic":"Bronquiectasias","difficulty":"médio","statement":"No acompanhamento ambulatorial de paciente com bronquiectasias estáveis, a cultura de escarro deve ser realizada periodicamente para monitorização microbiológica. Além disso, a pesquisa de micobactéria não tuberculosa pode ser necessária em situações específicas. Qual alternativa melhor expressa a importância desse seguimento?","correct":"B","alts":{"A":"A cultura de escarro não tem utilidade no seguimento.","B":"A monitorização microbiológica auxilia na identificação de colonização e na orientação do antibiótico.","C":"Só deve ser feita durante internações.","D":"Substitui a avaliação clínica e a tomografia.","E":"Serve apenas para confirmar tuberculose."},"exps":{"A":"Incorreta. Culturas periódicas identificam colonização e mudanças do perfil microbiológico.","B":"Correta. O resultado orienta antibióticos nas exacerbações e pode detectar Pseudomonas e micobactérias não tuberculosas.","C":"Incorreta. A coleta também integra o seguimento ambulatorial estável.","D":"Incorreta. Microbiologia complementa, mas não substitui, avaliação clínica e radiológica.","E":"Incorreta. A cultura bacteriana tem finalidade mais ampla; micobactérias exigem pesquisa própria."},"summary":"A vigilância microbiológica guia o tratamento e identifica colonização relevante.","memory":"Bronquiectasia: cultura estável para conhecer; cultura na exacerbação para tratar.","trap":"Não restringir cultura ao momento de internação."},
    {"n":2,"topic":"Bronquiectasias","difficulty":"difícil","statement":"Paciente apresenta bronquiectasias em lobo médio, língula e lobo inferior, com preservação dos lobos superiores. Considerando apenas a distribuição anatômica descrita, qual etiologia pode ser afastada segundo o gabarito da prova?","correct":"A","alts":{"A":"Discinesia ciliar primária.","B":"Fibrose cística.","C":"Doença do refluxo gastroesofágico.","D":"Micobacteriose não tuberculosa (síndrome de Lady Windermere).","E":"Bronquiectasia pós-infecciosa."},"exps":{"A":"Correta conforme o gabarito oficial, que associa a discinesia ciliar a predomínio basal. Na prática, distribuição anatômica isolada raramente exclui definitivamente uma etiologia.","B":"Incorreta. Fibrose cística pode produzir bronquiectasias, embora seja comum predomínio superior.","C":"Incorreta. Microaspiração pode comprometer lobos dependentes.","D":"Incorreta. Lobo médio e língula são distribuição clássica da síndrome de Lady Windermere.","E":"Incorreta. A forma pós-infecciosa pode ter distribuição variável."},"summary":"O gabarito marca discinesia ciliar, mas a distribuição isolada deve ser interpretada com cautela clínica.","memory":"Lobo médio + língula: lembre micobactéria não tuberculosa.","trap":"Resposta preservada conforme gabarito; não transformar padrão radiológico em exclusão absoluta fora do contexto da prova."},
    {"n":3,"topic":"Bronquiectasias","difficulty":"médio","statement":"Em paciente com bronquiectasias, tomografia mostra diâmetro traqueal normal e cloro no suor abaixo de 30 mEq/L. Quais etiologias são afastadas por esses dados?","correct":"B","alts":{"A":"Discinesia ciliar primária e ABPA.","B":"Síndrome de Mounier-Kuhn e fibrose cística.","C":"Síndrome de Williams-Campbell e fibrose cística.","D":"Micobacteriose e síndrome de Mounier-Kuhn.","E":"Discinesia ciliar e síndrome de Williams-Campbell."},"exps":{"A":"Incorreta. Esses exames não excluem discinesia ciliar nem ABPA.","B":"Correta. Mounier-Kuhn cursa com traqueobroncomegalia; cloro no suor <30 mmol/L torna fibrose cística improvável.","C":"Incorreta. Williams-Campbell decorre de deficiência cartilaginosa brônquica e não é excluída pelo diâmetro traqueal normal.","D":"Incorreta. Os achados não excluem micobacteriose.","E":"Incorreta. Nenhuma das duas é afastada pelos dados apresentados."},"summary":"Traqueia normal afasta traqueobroncomegalia; cloro no suor baixo torna fibrose cística improvável.","memory":"Mounier-Kuhn = traqueia grande; FC = cloro alto.","trap":"Não confundir Mounier-Kuhn com Williams-Campbell."},
    {"n":5,"topic":"Bronquiectasias","difficulty":"médio","statement":"Mulher de 35 anos com bronquiectasias apresenta três exacerbações infecciosas em 12 meses apesar de fisioterapia, sem Pseudomonas na cultura e sem asma ou DPOC associadas. Qual estratégia farmacológica pode reduzir exacerbações por efeito imunomodulador?","correct":"B","alts":{"A":"Prednisona oral contínua.","B":"Azitromicina em uso prolongado.","C":"Fluconazol profilático.","D":"Salbutamol em monoterapia.","E":"Rivaroxabana contínua."},"exps":{"A":"Incorreta. Corticoide sistêmico crônico não é estratégia de manutenção rotineira e causa toxicidade.","B":"Correta. Macrolídeo prolongado reduz exacerbações em exacerbadores frequentes, após excluir micobactéria não tuberculosa e avaliar QT/audição.","C":"Incorreta. Antifúngico não previne exacerbações bacterianas.","D":"Incorreta. Broncodilatador de resgate não substitui a estratégia anti-inflamatória/imunomoduladora.","E":"Incorreta. Anticoagulação não tem essa indicação."},"summary":"Exacerbador frequente sem Pseudomonas pode se beneficiar de macrolídeo prolongado.","memory":"Sem Pseudomonas + exacerba muito: pense em macrolídeo.","trap":"Antes do macrolídeo, pesquisar micobactéria não tuberculosa e riscos cardíaco/auditivo."},
    {"n":8,"topic":"Micoses pulmonares","difficulty":"fácil","statement":"Paciente com cavidade residual pós-tuberculose apresenta hemoptise recorrente e massa fúngica móvel intracavitária separada da parede por crescente aéreo. Qual é o diagnóstico mais provável?","correct":"C","alts":{"A":"Paracoccidioidomicose aguda.","B":"Histoplasmose mediastinal.","C":"Aspergiloma.","D":"Pneumocistose.","E":"Criptococose meníngea."},"exps":{"A":"Incorreta. PCM não forma tipicamente bola fúngica móvel em cavidade antiga.","B":"Incorreta. A forma mediastinal não explica a massa intracavitária móvel.","C":"Correta. Bola fúngica em cavidade prévia com sinal do crescente aéreo e hemoptise é aspergiloma.","D":"Incorreta. Pneumocistose causa vidro fosco difuso em imunossuprimidos.","E":"Incorreta. Não corresponde ao padrão pulmonar descrito."},"summary":"Aspergiloma coloniza cavidade pulmonar preexistente e frequentemente causa hemoptise.","memory":"Cavidade antiga + bola móvel + meia-lua = aspergiloma.","trap":"Não confundir o crescente aéreo do aspergiloma com sinais de recuperação da aspergilose invasiva."},
    {"n":9,"topic":"Micoses pulmonares","difficulty":"fácil","statement":"Homem de 51 anos, trabalhador rural, com tosse crônica, emagrecimento, rouquidão e lesões orais moriformes tem paracoccidioidomicose leve a moderada. Qual o tratamento de escolha?","correct":"B","alts":{"A":"Penicilina benzatina.","B":"Itraconazol.","C":"Oseltamivir.","D":"Ceftriaxona.","E":"Rifampicina isolada."},"exps":{"A":"Incorreta. Penicilina não trata Paracoccidioides.","B":"Correta. Itraconazol é primeira escolha nas formas leves a moderadas, geralmente por 9–18 meses conforme resposta e protocolo.","C":"Incorreta. Oseltamivir é antiviral para influenza.","D":"Incorreta. Ceftriaxona é antibacteriana.","E":"Incorreta. Rifampicina isolada não trata PCM."},"summary":"PCM leve/moderada: itraconazol; grave: anfotericina B seguida de manutenção.","memory":"Roda de leme e estomatite moriforme → itraconazol se estável.","trap":"A duração deve seguir gravidade, resposta clínica, sorologia e protocolo local."},
    {"n":10,"topic":"Micoses pulmonares","difficulty":"médio","statement":"Homem com AIDS avançada, febre, perda ponderal, dispneia e infiltrado micronodular difuso bilateral. Qual exame é especialmente útil e sensível para histoplasmose disseminada?","correct":"B","alts":{"A":"Baciloscopia do escarro.","B":"Antígeno de Histoplasma na urina.","C":"Prova tuberculínica.","D":"Espirometria.","E":"Dosagem de IgE sérica."},"exps":{"A":"Incorreta. Investiga tuberculose, não Histoplasma.","B":"Correta. Antígeno urinário tem alta sensibilidade na doença disseminada, sobretudo em imunossuprimidos.","C":"Incorreta. PPD avalia sensibilização ao Mycobacterium tuberculosis.","D":"Incorreta. Não define a etiologia infecciosa.","E":"Incorreta. IgE não confirma histoplasmose disseminada."},"summary":"Na AIDS com suspeita de histoplasmose disseminada, o antígeno urinário é exame-chave.","memory":"Histoplasma disseminado: procure antígeno na urina.","trap":"Culturas confirmam, mas podem demorar; antígeno acelera o diagnóstico."},
    {"n":11,"topic":"Micoses pulmonares","difficulty":"fácil","statement":"Homem com AIDS, CD4 de 78 células/mm³, dispneia subaguda, tosse seca, febre, hipoxemia e vidro fosco difuso bilateral. Qual o tratamento de primeira linha?","correct":"B","alts":{"A":"Itraconazol oral.","B":"Sulfametoxazol-trimetoprim.","C":"Fluconazol intravenoso.","D":"Piperacilina-tazobactam.","E":"Azitromicina."},"exps":{"A":"Incorreta. Não é primeira linha para Pneumocystis.","B":"Correta. SMX-TMP por 21 dias é primeira linha; adicionar corticoide se PaO2 <70 mmHg ou gradiente A-a ≥35 mmHg.","C":"Incorreta. Fluconazol não tem atividade adequada contra Pneumocystis.","D":"Incorreta. Não cobre o agente.","E":"Incorreta. Azitromicina não trata PCP."},"summary":"PCP na AIDS: SMX-TMP; corticoide quando há hipoxemia moderada/grave.","memory":"CD4 <200 + tosse seca + vidro fosco = PCP → SMX-TMP.","trap":"Não esquecer o critério gasométrico para corticoide adjuvante."},
    {"n":20,"topic":"Tromboembolismo pulmonar","difficulty":"médio","statement":"No tromboembolismo pulmonar agudo com repercussão hemodinâmica, qual é a principal causa do choque?","correct":"B","alts":{"A":"Aumento do retorno venoso ao ventrículo esquerdo.","B":"Obstrução da circulação pulmonar com sobrecarga aguda do ventrículo direito.","C":"Bradicardia reflexa grave.","D":"Vasodilatação sistêmica primária.","E":"Hipersecreção brônquica maciça."},"exps":{"A":"Incorreta. O enchimento do ventrículo esquerdo cai.","B":"Correta. A elevação abrupta da pós-carga do VD causa dilatação, isquemia, falência direita e queda do débito cardíaco.","C":"Incorreta. Taquicardia é mais comum e não é o mecanismo central.","D":"Incorreta. O choque é primariamente obstrutivo.","E":"Incorreta. Secreção brônquica não explica a instabilidade."},"summary":"TEP maciço causa choque obstrutivo por falência aguda do ventrículo direito.","memory":"TEP grave: obstrui pulmão, sobrecarrega VD, esvazia VE.","trap":"A hipotensão não decorre primariamente de vasodilatação."},
    {"n":21,"topic":"Tromboembolismo pulmonar","difficulty":"médio","statement":"Paciente com TEP de alto risco tem indicação teórica de trombólise. Qual opção representa contraindicação absoluta clássica ao trombolítico?","correct":"C","alts":{"A":"Idade acima de 75 anos.","B":"Uso prévio de AAS.","C":"AVC isquêmico há 3 meses.","D":"Hipertensão controlada.","E":"Cirurgia oftalmológica há 8 meses."},"exps":{"A":"Incorreta. Idade avançada eleva risco hemorrágico, mas isoladamente não é contraindicação absoluta.","B":"Incorreta. AAS aumenta sangramento, porém não é contraindicação absoluta isolada.","C":"Correta conforme o gabarito. AVC isquêmico recente é contraindicação maior/absoluta nos referenciais usados na prova.","D":"Incorreta. Hipertensão controlada não contraindica.","E":"Incorreta. O intervalo descrito não configura contraindicação absoluta clássica."},"summary":"Antes da trombólise, rastreie sangramento ativo, lesão intracraniana e AVC recente.","memory":"Trombólise: cérebro e sangramento vêm primeiro na lista de contraindicações.","trap":"Os limites temporais podem variar entre diretrizes; esta resposta segue o gabarito fornecido."},
    {"n":22,"topic":"Tromboembolismo pulmonar","difficulty":"fácil","statement":"Homem de 66 anos, no pós-operatório de fratura de fêmur, evolui com dispneia súbita, taquicardia e hipotensão persistente. Angio-TC confirma TEP extenso bilateral e não há contraindicações absolutas. Qual a conduta?","correct":"C","alts":{"A":"Alta com anticoagulante oral direto.","B":"Antibiótico e observação.","C":"Trombólise sistêmica associada à anticoagulação.","D":"Apenas oxigenoterapia.","E":"Corticoide venoso."},"exps":{"A":"Incorreta. Instabilidade exige reperfusão e monitorização hospitalar.","B":"Incorreta. Não trata a obstrução tromboembólica.","C":"Correta. TEP de alto risco com hipotensão persistente e sem contraindicação requer trombólise sistêmica e anticoagulação.","D":"Incorreta. Oxigênio é suporte, não tratamento definitivo.","E":"Incorreta. Corticoide não reperfunde a circulação pulmonar."},"summary":"TEP de alto risco instável: reperfusão imediata, geralmente trombólise sistêmica.","memory":"Hipotensão + TEP = trombólise se puder.","trap":"Cirurgia recente aumenta risco hemorrágico e exige avaliação individual, mas o enunciado declara ausência de contraindicação absoluta."},
    {"n":29,"topic":"Insuficiência respiratória aguda","difficulty":"fácil","statement":"Paciente com COVID-19, infiltrado bilateral difuso e relação PaO2/FiO2 de 60 mmHg sob PEEP adequada. Pela definição de Berlim, qual a classificação?","correct":"C","alts":{"A":"SDRA leve.","B":"SDRA moderada.","C":"SDRA grave.","D":"Edema cardiogênico isolado obrigatoriamente.","E":"Asma grave."},"exps":{"A":"Incorreta. SDRA leve tem P/F entre 200 e 300.","B":"Incorreta. Moderada tem P/F entre 100 e 200.","C":"Correta. P/F ≤100 com PEEP ≥5 cmH2O caracteriza SDRA grave.","D":"Incorreta. A definição exige que edema não seja totalmente explicado por falência cardíaca/sobrecarga.","E":"Incorreta. O padrão é de lesão alveolar difusa."},"summary":"P/F de 60 sob PEEP adequada corresponde a SDRA grave.","memory":"Berlim: 300 leve, 200 moderada, 100 grave.","trap":"Confirmar início agudo, opacidades bilaterais e origem não cardiogênica."},
    {"n":30,"topic":"Insuficiência respiratória aguda","difficulty":"fácil","statement":"Paciente com exacerbação de DPOC apresenta sonolência, FR 34, uso de musculatura acessória, pH 7,29, PaCO2 72 mmHg e PaO2 58 mmHg. Sem contraindicações, qual suporte ventilatório inicial é mais apropriado?","correct":"B","alts":{"A":"Oxigênio isolado por cateter nasal, sem monitorização.","B":"Ventilação não invasiva com pressão positiva.","C":"Trombólise sistêmica.","D":"Drenagem torácica.","E":"Apenas fisioterapia respiratória."},"exps":{"A":"Incorreta. Há acidose hipercápnica e fadiga; oxigênio isolado é insuficiente e deve ser titulado.","B":"Correta. VNI reduz trabalho respiratório, intubação e mortalidade na exacerbação de DPOC com acidose, se o paciente protege a via aérea.","C":"Incorreta. Não há indicação de TEP.","D":"Incorreta. Não há pneumotórax descrito.","E":"Incorreta. Medida isolada é insuficiente."},"summary":"DPOC exacerbada com acidose respiratória: VNI é primeira escolha quando possível.","memory":"DPOC + CO2 alto + pH baixo = VNI, se sem contraindicação.","trap":"Sonolência exige vigilância: incapacidade de proteger via aérea indica intubação."},
    {"n":31,"topic":"Insuficiência respiratória aguda","difficulty":"difícil","statement":"Paciente com DPOC estável tem gasometria em ar ambiente: pH 7,29; PaCO2 60 mmHg; PaO2 50 mmHg; HCO3 38 mEq/L; SatO2 84%. Qual alternativa melhor interpreta o distúrbio e a indicação de oxigênio domiciliar?","correct":"D","alts":{"A":"Acidose metabólica com ânion gap normal e alcalose respiratória; é candidato a oxigênio.","B":"Acidose respiratória crônica compensada; não é candidato a oxigênio.","C":"Alcalose respiratória aguda e acidose metabólica; não é candidato a oxigênio.","D":"Acidose respiratória crônica associada a alcalose metabólica; é candidato a oxigênio domiciliar.","E":"Alcalose metabólica compensada; não é candidato a oxigênio."},"exps":{"A":"Incorreta. PaCO2 está elevado, não reduzido.","B":"Incorreta. PaO2 de 50 mmHg em estabilidade preenche critério de oxigenoterapia prolongada.","C":"Incorreta. Não há alcalose respiratória.","D":"Correta conforme o gabarito. Hipercapnia com bicarbonato elevado indica componente crônico; HCO3 acima do esperado sugere alcalose metabólica adicional. PaO2 ≤55 indica oxigênio domiciliar, após confirmação em estabilidade.","E":"Incorreta. Há acidemia e hipercapnia."},"summary":"Hipoxemia crônica grave em DPOC estável indica oxigenoterapia domiciliar prolongada.","memory":"PaO2 ≤55: pense em O2 domiciliar, confirmado fora da exacerbação.","trap":"Reavaliar gasometria em estabilidade e titular oxigênio com cautela no retentor de CO2."}
  ]$data$::jsonb) AS x(n int, topic text, difficulty text, statement text, correct text, alts jsonb, exps jsonb, summary text, memory text, trap text)
  LOOP
    q_id := pg_temp.p3_uuid('pneumologia-p3-fechada-'||r.n);
    SELECT id INTO t_id FROM public.topics WHERE discipline_id=d_id AND name=r.topic LIMIT 1;
    IF t_id IS NULL THEN
      INSERT INTO public.topics(discipline_id,name) VALUES(d_id,r.topic) RETURNING id INTO t_id;
    END IF;
    INSERT INTO public.questions(id,discipline_id,topic_id,difficulty,statement,question_type,correct_answer,correct_answers,general_comment,summary,memory_tip,trap,reference,active,exam,image_url)
    VALUES(q_id,d_id,t_id,r.difficulty,r.statement,'single',r.correct,ARRAY[r.correct],
      'Resposta correta: '||r.correct||'. '||r.summary,r.summary,r.memory,r.trap,
      'Prova 3 de Pneumologia — prova e gabarito fornecidos; revisão educacional MedQuiz.',true,'P3',NULL)
    ON CONFLICT(id) DO UPDATE SET topic_id=EXCLUDED.topic_id,statement=EXCLUDED.statement,correct_answer=EXCLUDED.correct_answer,
      correct_answers=EXCLUDED.correct_answers,general_comment=EXCLUDED.general_comment,summary=EXCLUDED.summary,
      memory_tip=EXCLUDED.memory_tip,trap=EXCLUDED.trap,reference=EXCLUDED.reference,active=true,exam='P3';

    FOR a IN SELECT value FROM jsonb_array_elements(jsonb_build_array('A','B','C','D','E'))
    LOOP
      IF r.alts ? (a #>> '{}') THEN
        INSERT INTO public.alternatives(id,question_id,letter,text,explanation)
        VALUES(pg_temp.p3_uuid(q_id::text||(a #>> '{}')),q_id,a #>> '{}',r.alts->>(a #>> '{}'),r.exps->>(a #>> '{}'))
        ON CONFLICT(question_id,letter) DO UPDATE SET text=EXCLUDED.text,explanation=EXCLUDED.explanation;
      END IF;
    END LOOP;
  END LOOP;
END $$;

COMMIT;

SELECT count(*) AS total_fechadas_p3
FROM public.questions q JOIN public.disciplines d ON d.id=q.discipline_id
WHERE d.name='Pneumologia' AND q.exam='P3' AND q.id IN
  (SELECT pg_temp.p3_uuid('pneumologia-p3-fechada-'||n) FROM generate_series(1,34) n);
