-- Pneumologia — Prova 3 — 20 questões originalmente abertas.
-- Requer que a plataforma trate question_type='open'; não cria alternativas.
BEGIN;

CREATE OR REPLACE FUNCTION pg_temp.p3_uuid(seed text) RETURNS uuid
LANGUAGE sql IMMUTABLE AS $$
  SELECT (substr(md5(seed),1,8)||'-'||substr(md5(seed),9,4)||'-5'||substr(md5(seed),14,3)||'-a'||substr(md5(seed),18,3)||'-'||substr(md5(seed),21,12))::uuid
$$;

DO $$
DECLARE d_id uuid; r record; q_id uuid; t_id uuid;
BEGIN
  SELECT id INTO d_id FROM public.disciplines WHERE lower(name)=lower('Pneumologia') LIMIT 1;
  IF d_id IS NULL THEN RAISE EXCEPTION 'Disciplina Pneumologia não encontrada'; END IF;

  FOR r IN SELECT * FROM jsonb_to_recordset($data$[
    {"n":4,"topic":"Bronquiectasias","difficulty":"médio","statement":"Paciente com bronquiectasias apresenta dispneia mMRC 2, VEF1 em torno de 40% do previsto e múltiplas exacerbações, estando em uso de azitromicina. Classifique a gravidade e indique a otimização terapêutica.","answer":"Quadro de gravidade moderada no contexto da classificação funcional/escores de bronquiectasias, considerando mMRC 2, VEF1 reduzido e exacerbações. Deve-se otimizar com broncodilatador de longa duração quando houver dispneia/obstrução, manter a azitromicina prolongada se bem indicada e segura, e reforçar fisioterapia respiratória e higiene brônquica. É necessário revisar culturas, adesão, vacinação e causas tratáveis.","summary":"Gravidade integra sintomas, função pulmonar, exacerbações e microbiologia.","memory":"mMRC + VEF1 + exacerbações + colonização compõem o risco.","trap":"Não classificar apenas pelo VEF1 nem prescrever corticoide inalatório sem asma/DPOC."},
    {"n":6,"topic":"Bronquiectasias","difficulty":"médio","statement":"Mulher de 28 anos com tosse produtiva crônica, expectoração mucopurulenta diária, infecções recorrentes e tomografia com dilatação brônquica irreversível apresenta piora do volume/purulência do escarro, febre e dispneia. Explique a fisiopatologia e a abordagem da exacerbação infecciosa.","answer":"A bronquiectasia decorre do ciclo de Cole: depuração mucociliar deficiente favorece infecção persistente, inflamação neutrofílica e liberação de proteases, que destroem componentes elásticos e musculares da parede brônquica, gerando dilatação irreversível, retenção de secreções e novas infecções. Na exacerbação, colher escarro quando possível, intensificar fisioterapia/higiene brônquica, usar broncodilatador se indicado e iniciar antibiótico guiado por cultura prévia ou epidemiologia, cobrindo Pseudomonas quando colonização/risco, em geral por 10–14 dias conforme gravidade e resposta.","summary":"Infecção e inflamação perpetuam destruição brônquica e retenção de secreção.","memory":"Cole: infecção → inflamação → dano → secreção → nova infecção.","trap":"Evitar antibiótico sem considerar culturas prévias e risco de Pseudomonas."},
    {"n":7,"topic":"Bronquiectasias","difficulty":"difícil","statement":"Paciente de 42 anos com bronquiectasias difusas, quatro exacerbações no último ano e cultura com Pseudomonas aeruginosa. Explique por que a colonização piora o prognóstico e descreva o tratamento de manutenção.","answer":"Pseudomonas crônica aumenta a carga bacteriana e a inflamação neutrofílica, associa-se a mais exacerbações e internações, pior qualidade de vida, declínio funcional acelerado e maior mortalidade. O manejo inclui fisioterapia respiratória regular, tentativa de erradicação quando se trata de isolamento novo conforme protocolo, e, na infecção crônica com exacerbações frequentes, antibiótico inalatório (como colistina ou tobramicina, conforme disponibilidade/cultura). Macrolídeo prolongado pode ser associado em casos selecionados após excluir micobactéria não tuberculosa e avaliar QT/audição.","summary":"Pseudomonas crônica é marcador de alto risco e muda a estratégia de manutenção.","memory":"Pseudomonas: erradicar se nova; suprimir por via inalatória se crônica e exacerbadora.","trap":"Macrolídeo e antibiótico inalatório exigem seleção e monitorização; não são automáticos para todos."},
    {"n":12,"topic":"Micoses pulmonares","difficulty":"médio","statement":"Paciente jovem com febre arrastada, adinamia, perda ponderal, tosse e nódulos periféricos cavitados relata caça a tatus. Qual a hipótese diagnóstica principal e qual tratamento instituir?","answer":"A hipótese sugerida pelo gabarito é paracoccidioidomicose, devido à exposição rural/solo e ao vínculo epidemiológico descrito com tatus, associada ao quadro sistêmico e pulmonar. Deve-se confirmar por exame micológico/histopatológico e cultura. Formas leves a moderadas são tratadas preferencialmente com itraconazol; formas graves requerem anfotericina B, de preferência lipossomal quando indicada, seguida de consolidação/manutenção com itraconazol ou SMX-TMP. A duração depende da gravidade e resposta.","summary":"Epidemiologia rural mais doença pulmonar sistêmica deve levantar paracoccidioidomicose.","memory":"Tatu/solo rural + pulmão + mucosa: lembre Paracoccidioides.","trap":"Contato com tuberculose exige diagnóstico diferencial e confirmação etiológica."},
    {"n":13,"topic":"Micoses pulmonares","difficulty":"médio","statement":"Paciente com leveduras multigemantes em 'roda de leme' na coloração de Grocott. Informe o diagnóstico, as formas clínicas principais e o tratamento.","answer":"O achado confirma paracoccidioidomicose. A forma aguda/subaguda (juvenil) predomina em jovens e compromete sistema mononuclear-fagocítico, linfonodos, fígado e baço; a forma crônica do adulto é insidiosa, predominantemente pulmonar, frequentemente com lesões mucocutâneas. Casos leves/moderados: itraconazol; SMX-TMP é alternativa. Casos graves: anfotericina B seguida de tratamento oral de consolidação. A cura deve ser avaliada por critérios clínicos, micológicos, radiológicos e sorológicos.","summary":"Roda de leme é a assinatura morfológica da paracoccidioidomicose.","memory":"Juvenil = sistema reticuloendotelial; adulto = pulmão e mucosa.","trap":"Não encerrar terapia apenas porque os sintomas melhoraram."},
    {"n":14,"topic":"Micoses pulmonares","difficulty":"médio","statement":"Homem com tuberculose tratada há seis anos apresenta hemoptise recorrente e cavidade em lobo superior com massa intracavitária móvel e crescente aéreo. Dê o diagnóstico, explique a fisiopatologia e descreva o tratamento.","answer":"Trata-se de aspergiloma: conglomerado de hifas, muco e detritos que coloniza uma cavidade pulmonar preexistente, sem invasão tecidual típica, e pode lesar vasos brônquicos causando hemoptise. Assintomáticos podem ser observados. Hemoptise exige estabilização; embolização de artéria brônquica controla sangramento, mas pode recidivar. Ressecção cirúrgica é a opção definitiva em doença localizada, hemoptise relevante e reserva funcional adequada. Azólicos podem ser considerados em casos selecionados, sobretudo doença cavitária crônica associada ou inoperabilidade.","summary":"Aspergiloma é colonização de cavidade antiga; a hemoptise determina a intervenção.","memory":"TB antiga + bola móvel + sangue = aspergiloma.","trap":"Antifúngico isolado não substitui controle vascular/cirúrgico da hemoptise importante."},
    {"n":15,"topic":"Micoses pulmonares","difficulty":"difícil","statement":"Paciente com HIV, CD4 72, febre prolongada, perda ponderal, dispneia, infiltrado reticulonodular difuso, hepatoesplenomegalia e anemia. Qual a hipótese, o exame mais sensível e o tratamento conforme gravidade?","answer":"O quadro sugere histoplasmose disseminada em AIDS avançada. O antígeno de Histoplasma na urina é especialmente sensível e rápido; antígeno sérico, culturas, histopatologia e investigação de medula/tecidos complementam conforme o caso. Doença moderada/grave: anfotericina B lipossomal de indução, seguida de itraconazol. Doença leve/moderada selecionada pode receber itraconazol. Também é necessário iniciar/otimizar TARV no momento apropriado, pesquisar acometimento do SNC e manter terapia supressiva conforme resposta imune e diretriz.","summary":"AIDS + síndrome sistêmica reticuloendotelial + infiltrado difuso sugere histoplasmose disseminada.","memory":"Histoplasma disseminado: urina diagnostica; anfotericina induz; itraconazol mantém.","trap":"Não confundir com PCP, que em geral não causa hepatoesplenomegalia proeminente."},
    {"n":16,"topic":"Micoses pulmonares","difficulty":"médio","statement":"Homem de 43 anos, agricultor, com perda ponderal, tosse crônica, lesões orais dolorosas e infiltrado bilateral em 'asas de borboleta' nos campos médios. Qual a hipótese, os achados de suporte e o tratamento?","answer":"A principal hipótese é paracoccidioidomicose crônica do adulto. Sustentam o diagnóstico a exposição rural, evolução insidiosa pulmonar, emagrecimento e estomatite moriforme/úlceras orais, além do padrão radiológico bilateral. Confirmar por exame direto, histopatologia e/ou cultura. Formas leves/moderadas: itraconazol; SMX-TMP é alternativa. Formas graves: anfotericina B, seguida de manutenção oral prolongada.","summary":"Pulmão crônico e lesão oral moriforme em trabalhador rural são clássicos de PCM.","memory":"PCM do adulto: pulmão + boca + campo.","trap":"Tuberculose e neoplasia são diferenciais relevantes e podem coexistir."},
    {"n":17,"topic":"Micoses pulmonares","difficulty":"difícil","statement":"Homem com HIV sem TARV regular apresenta dispneia progressiva por três semanas, tosse seca, febre baixa, SatO2 88% e vidro fosco bilateral difuso com discreta poupança periférica. Informe diagnóstico, fisiopatologia, métodos diagnósticos e tratamento, incluindo corticoide.","answer":"O diagnóstico mais provável é pneumonia por Pneumocystis jirovecii. O microrganismo prolifera no alvéolo em imunossupressão celular, produz exsudato proteináceo e lesão da interface alvéolo-capilar, reduzindo difusão e causando hipoxemia. Diagnóstico por escarro induzido ou lavado broncoalveolar com imunofluorescência/PCR; beta-D-glucana e DHL apoiam, mas não são específicos. Tratar com SMX-TMP por 21 dias. Associar corticoide idealmente nas primeiras 72 horas quando PaO2 em ar ambiente <70 mmHg ou gradiente A-a ≥35 mmHg. Oferecer suporte de oxigênio e organizar TARV/profilaxia secundária.","summary":"PCP é pneumonia oportunista alveolar difusa ligada a CD4 baixo.","memory":"Vidro fosco + tosse seca + HIV → SMX-TMP 21 dias.","trap":"Corticoide depende da gravidade gasométrica, não apenas da imagem."},
    {"n":18,"topic":"Micoses pulmonares","difficulty":"médio","statement":"Homem rural, tabagista e etilista, com tosse crônica, emagrecimento, rouquidão, úlceras orais dolorosas e infiltrado pulmonar bilateral em campos médios. Explique por que sugere paracoccidioidomicose, as formas clínicas e o tratamento.","answer":"A exposição rural, doença pulmonar crônica, estomatite ulcerada/moriforme e possível acometimento laríngeo com rouquidão formam o quadro típico de PCM crônica do adulto. A forma aguda/subaguda ocorre mais em jovens e envolve linfonodos e órgãos do sistema mononuclear-fagocítico; a crônica predomina em adultos e compromete pulmões e mucosas. Tratar formas leves/moderadas com itraconazol (SMX-TMP como alternativa) e graves com anfotericina B seguida de consolidação oral.","summary":"A forma crônica da PCM combina pulmão e mucosa em adulto exposto ao meio rural.","memory":"Rouquidão + boca moriforme + pulmão rural = PCM.","trap":"Tabagismo aumenta a necessidade de excluir câncer e outras causas de lesão mucosa."},
    {"n":19,"topic":"Micoses pulmonares","difficulty":"difícil","statement":"Paciente neutropênico após quimioterapia apresenta febre persistente, dor torácica, hemoptise e nódulos com halo de vidro fosco. Qual subtipo de aspergilose é provável? Diferencie de aspergiloma e ABPA e descreva o tratamento.","answer":"É aspergilose pulmonar invasiva angioinvasiva; o halo representa hemorragia ao redor de foco em paciente neutropênico. Tratar precocemente com voriconazol ou isavuconazol; anfotericina B lipossomal é alternativa, além de reduzir imunossupressão/reverter neutropenia quando possível. Aspergiloma é bola fúngica saprofítica em cavidade prévia e é manejado conforme hemoptise com observação, embolização e/ou cirurgia. ABPA é hipersensibilidade em asma/fibrose cística, com IgE elevada e bronquiectasias centrais, tratada principalmente com corticoide sistêmico e, em selecionados, azólico/biológico.","summary":"Halo em neutropênico é emergência para aspergilose invasiva.","memory":"Invasiva invade vaso; aspergiloma ocupa cavidade; ABPA é alergia.","trap":"Não aguardar confirmação tardia para iniciar terapia em alta suspeita."},
    {"n":23,"topic":"Tromboembolismo pulmonar","difficulty":"médio","statement":"Paciente idoso, hipertenso, no pós-operatório de correção de fratura de fêmur apresenta dispneia súbita e hipoxemia, mas está hemodinamicamente estável. Qual exame confirma o diagnóstico e qual a conduta?","answer":"A angiotomografia pulmonar é o exame confirmatório de escolha quando não há contraindicação a contraste; cintilografia V/Q é alternativa em situações selecionadas. Em paciente estável, iniciar anticoagulação terapêutica conforme probabilidade clínica e risco hemorrágico, com HBPM, HNF ou anticoagulante oral direto conforme função renal, contexto cirúrgico e possibilidade de intervenção. Trombólise não é rotineira sem instabilidade; estratificar VD, troponina e PESI.","summary":"TEP estável é confirmado por angio-TC e tratado principalmente com anticoagulação.","memory":"Estável: anticoagula; instável: avalia reperfusão.","trap":"Pós-operatório exige ponderar sangramento e escolher anticoagulante reversível quando necessário."},
    {"n":24,"topic":"Tromboembolismo pulmonar","difficulty":"difícil","statement":"Em caso clínico de suspeita de TEP com PESI de baixa mortalidade, determine a probabilidade, os exames e a conduta farmacológica inicial.","answer":"O gabarito classifica a probabilidade como intermediária e o risco prognóstico como baixo pelo PESI. A investigação deve seguir probabilidade pré-teste: D-dímero ajustado à idade se baixa/intermediária e angio-TC se positivo; em probabilidade alta, angio-TC diretamente. Ecocardiograma e biomarcadores avaliam repercussão do VD, não excluem TEP estável isoladamente. Confirmado TEP de baixo risco e com critérios sociais/hemorrágicos favoráveis, pode-se usar DOAC ambulatorial; se indisponível, anticoagulação parenteral com transição para varfarina.","summary":"Wells estima probabilidade diagnóstica; PESI estima prognóstico.","memory":"Wells pergunta 'é TEP?'; PESI pergunta 'qual o risco?'.","trap":"Não usar D-dímero para confirmar TEP nem confundir probabilidade com gravidade."},
    {"n":25,"topic":"Tromboembolismo pulmonar","difficulty":"difícil","statement":"Paciente com câncer, hemoptise, imobilização e taquicardia tem suspeita de TEP. Calcule/interprete Wells, indique exames e conduta terapêutica.","answer":"Conforme o gabarito, o TEP é provável no Wells simplificado e tem probabilidade intermediária no escore original (5,5, pelos elementos fornecidos). Deve-se solicitar angio-TC; ultrassom venoso pode demonstrar TVP e ecocardiograma/biomarcadores estratificam repercussão do VD. Se a probabilidade clínica é alta e o risco hemorrágico permite, anticoagulação pode ser iniciada enquanto se confirma. A HNF é útil quando há possibilidade de reperfusão ou alto risco de sangramento por rápida reversão. Trombólise é indicada no alto risco com instabilidade; em risco intermediário, fica para deterioração/resgate, não apenas por angio-TC positiva.","summary":"A conduta combina probabilidade pré-teste, confirmação e estratificação hemodinâmica.","memory":"Trombólise trata instabilidade, não simplesmente extensão anatômica.","trap":"O texto do gabarito antigo amplia trombólise em disfunção de VD; práticas atuais favorecem anticoagulação e vigilância no paciente estável."},
    {"n":26,"topic":"Tromboembolismo pulmonar","difficulty":"difícil","statement":"Homem no quinto dia após artroplastia de quadril tem TEP bilateral confirmado, PA 82/58, FC 126 e pré-síncope. Explique a fisiopatologia da instabilidade e o tratamento agudo, incluindo trombólise.","answer":"A obstrução vascular pulmonar aumenta abruptamente a resistência e a pós-carga do VD. O VD dilata, aumenta tensão parietal e consumo de oxigênio, pode isquemiar; o septo desvia para a esquerda, reduzindo enchimento do VE e débito cardíaco, culminando em choque obstrutivo. É TEP de alto risco: suporte de oxigenação e hemodinâmica, anticoagulação com HNF e reperfusão urgente. Trombólise sistêmica é primeira opção se não houver contraindicação; em cirurgia recente, o risco hemorrágico deve ser avaliado e embolectomia por cateter/cirúrgica pode ser preferível ou usada se trombólise falhar.","summary":"No TEP maciço, a falência aguda do VD derruba o débito do VE.","memory":"Pós-carga do VD sobe → VD falha → VE esvazia → choque.","trap":"Cirurgia recente pode tornar a escolha da reperfusão complexa."},
    {"n":27,"topic":"Tromboembolismo pulmonar","difficulty":"médio","statement":"Mulher obesa, usuária de anticoncepcional, hemodinamicamente estável, com TEP segmentar confirmado. Diferencie manejo agudo e tardio, incluindo duração e fatores decisórios.","answer":"Na fase aguda, iniciar anticoagulação terapêutica; DOAC é opção prática em estáveis, enquanto HBPM/HNF é escolhida em gravidez, insuficiência renal, câncer específico, alto risco hemorrágico ou possibilidade de procedimento. Avaliar PESI, VD e biomarcadores para local de cuidado. Na manutenção, anticoagular por pelo menos três meses. Se o evento foi provocado por fator transitório removível, três meses costuma bastar; TEP não provocado, fator persistente, recorrência, câncer ou trombofilia de alto risco favorecem extensão, sempre contrapondo risco de recorrência e sangramento.","summary":"Todo TEP recebe fase inicial; a causa e o risco definem por quanto tempo manter.","memory":"Três meses é o piso; persistência do risco pode tornar o tratamento estendido.","trap":"Suspender anticoncepcional estrogênico e discutir método alternativo."},
    {"n":28,"topic":"Tromboembolismo pulmonar","difficulty":"difícil","statement":"Mulher com neoplasia, TEP lobar bilateral, pressão preservada e episódio de quase síncope. Descreva a repercussão sobre circulação pulmonar/coração direito e como o risco orienta o tratamento.","answer":"Os trombos elevam resistência vascular pulmonar e pós-carga do VD, podendo causar dilatação e disfunção direita, isquemia, desvio septal e redução do enchimento do VE. Como não há hipotensão persistente, não é alto risco; deve-se estratificar com PESI/sPESI, troponina/BNP e ecocardiograma ou relação VD/VE na TC. A base é anticoagulação plena e monitorização. Se houver disfunção do VD e biomarcador positivo, trata-se de risco intermediário-alto, exigindo vigilância para deterioração; trombólise de resgate/reperfusão é reservada à instabilidade, considerando alto risco hemorrágico.","summary":"No TEP estável, VD e biomarcadores refinam o risco e a intensidade da vigilância.","memory":"Pressão define alto risco; VD + troponina subdividem o intermediário.","trap":"Quase síncope alerta, mas não equivale isoladamente a choque persistente."},
    {"n":32,"topic":"Insuficiência respiratória aguda","difficulty":"difícil","statement":"Homem de 70 anos com COVID-19, relação P/F 190, linfopenia, PCR 180, ferritina 1800 e D-dímero 800. Explique PCR e D-dímero, cite quatro fatores clínicos de gravidade, descreva o achado de imagem esperado e a orientação à filha sintomática.","answer":"PCR alta reflete resposta inflamatória sistêmica mediada por citocinas, especialmente IL-6; D-dímero elevado traduz ativação da coagulação e fibrinólise associada a endoteliopatia/inflamação, mas não confirma TEP isoladamente. Fatores clínicos incluem idade avançada, obesidade, diabetes, doença cardiovascular/renal/pulmonar, imunossupressão e tabagismo. Esperam-se opacidades bilaterais em vidro fosco, periféricas/subpleurais, podendo haver consolidação. A filha deve usar máscara, reduzir contato, realizar testagem conforme janela/protocolo vigente e observar sinais de alarme; isolamento e recomendações temporais devem seguir a autoridade sanitária atual.","summary":"COVID grave combina inflamação, lesão alveolar e imunotrombose.","memory":"PCR inflama; D-dímero coagula/fibrinolisa; vidro fosco aparece.","trap":"D-dímero elevado não autoriza anticoagulação terapêutica sem avaliação clínica."},
    {"n":33,"topic":"Insuficiência respiratória aguda","difficulty":"médio","statement":"Homem de 71 anos com DPOC avançado, exacerbação infecciosa, sonolência, pH 7,28, PaCO2 68 e PaO2 54. Classifique a insuficiência respiratória e descreva o tratamento ventilatório.","answer":"É insuficiência respiratória aguda hipercápnica (tipo II), com acidose respiratória e hipoxemia, provavelmente aguda sobre crônica. Oferecer oxigênio controlado visando SatO2 88–92%, broncodilatadores de curta ação, corticoide sistêmico e antibiótico quando indicado por purulência/gravidade. VNI é primeira escolha se o paciente coopera e protege a via aérea, pois reduz trabalho respiratório e intubação. Reavaliar precocemente; piora do sensório, instabilidade, secreção incontrolável ou falha gasométrica indicam intubação.","summary":"DPOC com acidose hipercápnica responde à VNI quando não há contraindicação.","memory":"Tipo II = CO2 alto; alvo de O2 88–92%.","trap":"Sonolência leve pode melhorar com VNI, mas rebaixamento incapacitante exige via aérea definitiva."},
    {"n":34,"topic":"Insuficiência respiratória aguda","difficulty":"difícil","statement":"Paciente com DPOC, pneumonia em base direita e gasometria sob Venturi 50%: pH 7,27, PaCO2 53, PaO2 120, HCO3 26. Explique mecanismos/causas da IRpA e indique a conduta inicial.","answer":"Há mecanismo misto: baixa relação V/Q ou shunt pela consolidação pneumônica e hipoventilação alveolar na exacerbação da DPOC, evidenciada por hipercapnia e acidemia. A relação P/F é aproximadamente 240 sob FiO2 0,50, mas deve ser interpretada no contexto do oxigênio ofertado. Reduzir FiO2 de forma titulada para alvo 88–92%, iniciar VNI se não houver contraindicação, monitorar gasometria e tratar DPOC/pneumonia com broncodilatadores, corticoide sistêmico e antibiótico apropriado. Intubar se houver falha da VNI ou incapacidade de proteger a via aérea.","summary":"Pneumonia piora V/Q; DPOC reduz ventilação alveolar: o resultado pode ser IRpA mista.","memory":"Consolidação baixa V/Q; hipoventilação sobe CO2.","trap":"PaO2 de 120 não exclui insuficiência respiratória quando obtida sob FiO2 de 50%."}
  ]$data$::jsonb) AS x(n int,topic text,difficulty text,statement text,answer text,summary text,memory text,trap text)
  LOOP
    q_id := pg_temp.p3_uuid('pneumologia-p3-aberta-'||r.n);
    SELECT id INTO t_id FROM public.topics WHERE discipline_id=d_id AND name=r.topic LIMIT 1;
    IF t_id IS NULL THEN
      INSERT INTO public.topics(discipline_id,name) VALUES(d_id,r.topic) RETURNING id INTO t_id;
    END IF;
    INSERT INTO public.questions(id,discipline_id,topic_id,difficulty,statement,question_type,correct_answer,correct_answers,general_comment,summary,memory_tip,trap,reference,active,exam,image_url)
    VALUES(q_id,d_id,t_id,r.difficulty,r.statement,'open',NULL,ARRAY[]::text[],r.answer,r.summary,r.memory,r.trap,
      'Prova 3 de Pneumologia — questão aberta e resposta-modelo revisada no padrão MedQuiz.',false,'P3',NULL)
    ON CONFLICT(id) DO UPDATE SET topic_id=EXCLUDED.topic_id,statement=EXCLUDED.statement,question_type='open',correct_answer=NULL,
      correct_answers=ARRAY[]::text[],general_comment=EXCLUDED.general_comment,summary=EXCLUDED.summary,
      memory_tip=EXCLUDED.memory_tip,trap=EXCLUDED.trap,reference=EXCLUDED.reference,active=false,exam='P3';
  END LOOP;
END $$;

COMMIT;

SELECT count(*) AS total_abertas_p3
FROM public.questions q JOIN public.disciplines d ON d.id=q.discipline_id
WHERE d.name='Pneumologia' AND q.exam='P3' AND q.question_type='open';
