-- Pneumologia — Prova 3 — 20 questões abertas transformadas em objetivas.
-- Este arquivo é independente do payload 02 e usa IDs próprios.
BEGIN;

CREATE OR REPLACE FUNCTION pg_temp.p3_uuid(seed text) RETURNS uuid
LANGUAGE sql IMMUTABLE AS $$
  SELECT (substr(md5(seed),1,8)||'-'||substr(md5(seed),9,4)||'-5'||substr(md5(seed),14,3)||'-a'||substr(md5(seed),18,3)||'-'||substr(md5(seed),21,12))::uuid
$$;

DO $$
DECLARE d_id uuid; r record; q_id uuid; t_id uuid; a jsonb;
BEGIN
  SELECT id INTO d_id FROM public.disciplines WHERE lower(name)=lower('Pneumologia') LIMIT 1;
  IF d_id IS NULL THEN RAISE EXCEPTION 'Disciplina Pneumologia não encontrada'; END IF;

  FOR r IN SELECT * FROM jsonb_to_recordset($data$[
    {"n":4,"topic":"Bronquiectasias","difficulty":"médio","statement":"Paciente com bronquiectasias, dispneia mMRC 2, VEF1 de 40% e exacerbações frequentes já usa azitromicina. Qual avaliação e otimização são mais adequadas?","correct":"B","alts":[{"l":"A","t":"Doença leve; suspender fisioterapia e manter apenas salbutamol.","e":"Incorreta. Função reduzida e exacerbações afastam baixo risco; higiene brônquica continua essencial."},{"l":"B","t":"Gravidade pelo menos moderada; considerar broncodilatador de longa duração, manter macrolídeo se indicado e reforçar fisioterapia.","e":"Correta. A conduta integra dispneia, obstrução, exacerbações e medidas de depuração brônquica."},{"l":"C","t":"Doença grave apenas pelo VEF1; iniciar corticoide oral contínuo.","e":"Incorreta. A gravidade não depende de um único dado e corticoide sistêmico crônico não é rotina."},{"l":"D","t":"Azitromicina contraindica qualquer broncodilatador.","e":"Incorreta. As estratégias podem ser combinadas conforme sintomas e obstrução."}],"general":"A estratificação de bronquiectasias combina sintomas, VEF1, exacerbações, extensão radiológica, idade e microbiologia. O tratamento deve otimizar depuração brônquica, doença de base e terapias para o fenótipo exacerbador.","summary":"Gravidade e tratamento são multidimensionais.","memory":"mMRC + VEF1 + exacerbações + microbiologia.","trap":"Não usar corticoide inalatório sem asma/DPOC associada."},
    {"n":6,"topic":"Bronquiectasias","difficulty":"médio","statement":"Qual alternativa descreve corretamente o ciclo fisiopatológico da bronquiectasia e o manejo de uma exacerbação purulenta?","correct":"C","alts":[{"l":"A","t":"Broncoespasmo reversível isolado; tratar apenas com corticoide inalatório.","e":"Incorreta. Bronquiectasia envolve dilatação irreversível, infecção e inflamação crônicas."},{"l":"B","t":"Fibrose alveolar primária; usar antifúngico empírico por 48 horas.","e":"Incorreta. O dano central é brônquico e o antibiótico deve considerar microbiologia."},{"l":"C","t":"Infecção e inflamação neutrofílica destroem a parede brônquica e perpetuam retenção de secreção; colher escarro, intensificar higiene brônquica e usar antibiótico guiado por risco/cultura.","e":"Correta. É o ciclo de Cole e a abordagem recomendada da exacerbação infecciosa."},{"l":"D","t":"Dilatação brônquica fisiológica pelo envelhecimento; observar sem fisioterapia ou antibiótico.","e":"Incorreta. A piora clínica com purulência e febre caracteriza exacerbação tratável."}],"general":"O ciclo de Cole liga falha de depuração, infecção, inflamação neutrofílica, destruição da parede e nova retenção de secreções. Exacerbações requerem higiene brônquica e antibiótico geralmente por 10–14 dias, ajustado à cultura e à gravidade.","summary":"O ciclo infecção–inflamação mantém a bronquiectasia.","memory":"Cole: infecta, inflama, destrói, retém, reinfecta.","trap":"Cobrir Pseudomonas quando houver colonização ou risco, não automaticamente."},
    {"n":7,"topic":"Bronquiectasias","difficulty":"difícil","statement":"Em bronquiectasias com quatro exacerbações anuais e infecção crônica por Pseudomonas aeruginosa, qual estratégia de manutenção é mais apropriada?","correct":"D","alts":[{"l":"A","t":"Suspender fisioterapia para evitar disseminação bacteriana.","e":"Incorreta. Fisioterapia é pilar da depuração de secreções."},{"l":"B","t":"Prednisona oral contínua como monoterapia.","e":"Incorreta. Não reduz especificamente a carga de Pseudomonas e causa toxicidade."},{"l":"C","t":"Fluconazol profilático e cultura apenas quando internar.","e":"Incorreta. Fluconazol não trata Pseudomonas e vigilância microbiológica é necessária."},{"l":"D","t":"Fisioterapia regular e antibiótico inalatório; considerar macrolídeo em selecionados após excluir micobactéria não tuberculosa.","e":"Correta. A supressão inalatória reduz carga bacteriana/exacerbações; macrolídeo exige triagem e monitorização."}],"general":"Pseudomonas crônica é associada a mais inflamação, exacerbações, declínio funcional e mortalidade. Novo isolamento pode motivar erradicação; infecção crônica em exacerbador favorece antibiótico inalatório.","summary":"Pseudomonas muda prognóstico e terapia.","memory":"Nova: erradicar; crônica exacerbadora: suprimir.","trap":"Macrolídeo sem excluir micobactéria pode induzir resistência."},
    {"n":12,"topic":"Micoses pulmonares","difficulty":"médio","statement":"Jovem com febre arrastada, perda de peso, tosse, nódulos periféricos cavitados e hábito de caçar tatus. Qual combinação diagnóstica e terapêutica é a melhor?","correct":"A","alts":[{"l":"A","t":"Paracoccidioidomicose; itraconazol se leve/moderada e anfotericina B seguida de manutenção se grave.","e":"Correta conforme o gabarito e o vínculo epidemiológico, devendo haver confirmação micológica/histológica."},{"l":"B","t":"Pneumocistose; fluconazol por sete dias.","e":"Incorreta. PCP ocorre sobretudo em imunossupressão e é tratada com SMX-TMP."},{"l":"C","t":"Aspergiloma; corticoide sistêmico isolado.","e":"Incorreta. Aspergiloma ocupa cavidade preexistente; corticoide isolado pode piorar micose."},{"l":"D","t":"Histoplasmose mediastinal; azitromicina contínua.","e":"Incorreta. Azitromicina não trata Histoplasma."}],"general":"A exposição rural/solo, a epidemiologia relacionada a tatus e a doença pulmonar sistêmica sugerem paracoccidioidomicose. Tuberculose permanece diferencial e a etiologia deve ser confirmada.","summary":"PCM deve ser lembrada em exposição rural com doença pulmonar crônica/subaguda.","memory":"Tatu + campo + pulmão = Paracoccidioides.","trap":"Não ignorar tuberculose por causa da pista epidemiológica."},
    {"n":13,"topic":"Micoses pulmonares","difficulty":"médio","statement":"Leveduras multigemantes em 'roda de leme' foram vistas no Grocott. Qual alternativa reúne diagnóstico, formas e tratamento corretos?","correct":"C","alts":[{"l":"A","t":"Histoplasmose; apenas forma pulmonar; fluconazol.","e":"Incorreta. Roda de leme é típica de Paracoccidioides."},{"l":"B","t":"Aspergilose; forma alérgica e invasiva; penicilina.","e":"Incorreta. Aspergillus forma hifas septadas e não responde a penicilina."},{"l":"C","t":"Paracoccidioidomicose; forma aguda/subaguda juvenil e crônica do adulto; itraconazol nas leves/moderadas e anfotericina B nas graves.","e":"Correta. Resume morfologia, classificação clínica e tratamento por gravidade."},{"l":"D","t":"Pneumocistose; forma juvenil e adulta; SMX-TMP por seis meses.","e":"Incorreta. PCP não apresenta roda de leme e a duração habitual é 21 dias."}],"general":"A forma juvenil compromete mais linfonodos e sistema mononuclear-fagocítico; a crônica do adulto predomina em pulmões e mucosas. O seguimento de PCM utiliza critérios clínicos, radiológicos, micológicos e sorológicos.","summary":"Roda de leme confirma PCM.","memory":"Juvenil = linfonodo; adulto = pulmão/mucosa.","trap":"A duração do tratamento vai além da melhora sintomática."},
    {"n":14,"topic":"Micoses pulmonares","difficulty":"médio","statement":"Após tuberculose tratada, paciente tem hemoptise e massa móvel dentro de cavidade pulmonar com crescente aéreo. Qual alternativa descreve corretamente fisiopatologia e manejo?","correct":"B","alts":[{"l":"A","t":"Aspergilose invasiva por angioinvasão; tratar todo caso com corticoide.","e":"Incorreta. O cenário é de colonização cavitária e corticoide não é tratamento."},{"l":"B","t":"Aspergiloma por colonização saprofítica de cavidade; observar se assintomático e controlar hemoptise com embolização/cirurgia conforme caso.","e":"Correta. A massa fúngica pode erodir vasos brônquicos e cirurgia é definitiva em selecionados."},{"l":"C","t":"ABPA por hipersensibilidade; indicar lobectomia imediata para todos.","e":"Incorreta. ABPA ocorre em asma/FC e é tratada principalmente com corticoide."},{"l":"D","t":"Histoplasmoma; anticoagular para prevenir sangramento.","e":"Incorreta. Anticoagulação pode agravar a hemoptise e o padrão é de aspergiloma."}],"general":"O aspergiloma é uma bola de hifas e detritos em cavidade antiga. Embolização pode controlar hemoptise; ressecção é definitiva em doença localizada com reserva adequada. Azólicos são adjuvantes em cenários selecionados.","summary":"Aspergiloma coloniza cavidade e sangra por vasos brônquicos.","memory":"Cavidade antiga + bola móvel = aspergiloma.","trap":"Hemoptise maciça exige estabilização antes da terapia definitiva."},
    {"n":15,"topic":"Micoses pulmonares","difficulty":"difícil","statement":"Paciente com AIDS, CD4 72, febre prolongada, hepatoesplenomegalia, anemia e infiltrado reticulonodular difuso. Qual opção é mais completa?","correct":"D","alts":[{"l":"A","t":"PCP; confirmar por espirometria e tratar com itraconazol.","e":"Incorreta. Espirometria não define etiologia e hepatoesplenomegalia aponta para doença disseminada."},{"l":"B","t":"Tuberculose latente; PPD e nenhuma terapia imediata.","e":"Incorreta. O quadro é doença sistêmica ativa grave."},{"l":"C","t":"ABPA; IgE total e corticoide inalatório.","e":"Incorreta. ABPA se associa a asma/FC, não ao padrão sistêmico descrito."},{"l":"D","t":"Histoplasmose disseminada; antígeno urinário e anfotericina B lipossomal nas formas graves, seguida de itraconazol.","e":"Correta. É a apresentação clássica em imunossupressão avançada."}],"general":"O antígeno urinário é rápido e sensível na histoplasmose disseminada em AIDS. Cultura/histopatologia complementam; avaliar SNC, TARV e necessidade de manutenção prolongada.","summary":"Histoplasmose disseminada envolve pulmão e sistema reticuloendotelial.","memory":"AIDS + fígado/baço + pulmão = antígeno de Histoplasma na urina.","trap":"PCP costuma ter tosse seca e vidro fosco, mas não hepatoesplenomegalia marcante."},
    {"n":16,"topic":"Micoses pulmonares","difficulty":"médio","statement":"Agricultor com emagrecimento, tosse crônica, úlceras orais dolorosas e infiltrado bilateral em campos médios deve receber qual abordagem?","correct":"A","alts":[{"l":"A","t":"Suspeitar de PCM crônica, confirmar etiologia; usar itraconazol se leve/moderada e anfotericina B seguida de manutenção se grave.","e":"Correta. Epidemiologia, pulmão e estomatite moriforme sustentam PCM."},{"l":"B","t":"Diagnosticar PCP e usar SMX-TMP por 21 dias sem investigação.","e":"Incorreta. Não há contexto de imunossupressão e lesão oral não é típica de PCP."},{"l":"C","t":"Diagnosticar aspergiloma e anticoagular.","e":"Incorreta. Não há cavidade com bola fúngica e anticoagulação pode piorar sangramento."},{"l":"D","t":"Considerar apenas câncer oral e ignorar o pulmão.","e":"Incorreta. Câncer é diferencial, mas o conjunto sugere micose sistêmica e requer investigação integrada."}],"general":"PCM crônica do adulto é comum em homens expostos ao meio rural e combina doença pulmonar insidiosa com lesões mucocutâneas. Exame direto, histologia e cultura confirmam.","summary":"Pulmão e boca em trabalhador rural: pense PCM.","memory":"Estomatite moriforme é pista forte.","trap":"Tuberculose e neoplasia podem coexistir e devem ser excluídas."},
    {"n":17,"topic":"Micoses pulmonares","difficulty":"difícil","statement":"Homem com HIV sem TARV tem tosse seca, hipoxemia e vidro fosco bilateral difuso. Qual opção traz diagnóstico, confirmação e tratamento adequados?","correct":"B","alts":[{"l":"A","t":"Histoplasmose; PPD e penicilina.","e":"Incorreta. PPD não diagnostica Histoplasma e penicilina não trata fungos."},{"l":"B","t":"Pneumocistose; escarro induzido ou LBA com PCR/imunofluorescência; SMX-TMP por 21 dias e corticoide se PaO2 <70 ou A-a ≥35.","e":"Correta. Integra o padrão clínico, diagnóstico etiológico e critério de corticoide."},{"l":"C","t":"ABPA; cultura bacteriana e fluconazol.","e":"Incorreta. ABPA requer asma/FC e não é tratada com fluconazol."},{"l":"D","t":"Aspergiloma; ressecção imediata da bola fúngica.","e":"Incorreta. Não há cavidade ou massa intracavitária."}],"general":"PCP produz exsudato alveolar e dano da interface alvéolo-capilar, causando grande hipoxemia com ausculta pouco exuberante. Beta-D-glucana apoia, mas não é específica.","summary":"PCP: vidro fosco, HIV e hipoxemia.","memory":"SMX-TMP 21 dias; corticoide pela gasometria.","trap":"Não indicar corticoide apenas porque há vidro fosco."},
    {"n":18,"topic":"Micoses pulmonares","difficulty":"médio","statement":"Qual opção explica melhor tosse crônica, rouquidão, emagrecimento, úlceras orais e infiltrado bilateral em homem rural?","correct":"C","alts":[{"l":"A","t":"Forma juvenil de PCM, limitada exclusivamente a linfonodos.","e":"Incorreta. O paciente adulto com pulmão/mucosa tem forma crônica."},{"l":"B","t":"Criptococose meníngea, tratada apenas com azitromicina.","e":"Incorreta. O quadro não é meníngeo e azitromicina não trata Cryptococcus."},{"l":"C","t":"PCM crônica do adulto com possível acometimento laríngeo; itraconazol nas formas não graves e anfotericina B nas graves.","e":"Correta. O conjunto epidemiológico e clínico é clássico."},{"l":"D","t":"Pneumocistose, pois toda micose pulmonar causa úlcera oral.","e":"Incorreta. PCP não causa tipicamente estomatite moriforme."}],"general":"A PCM tem forma aguda/subaguda juvenil, mais linforreticular, e crônica do adulto, pulmonar e mucocutânea. Rouquidão pode representar acometimento laríngeo.","summary":"PCM crônica une exposição rural, pulmão e mucosa.","memory":"Campo + boca + rouquidão = PCM crônica.","trap":"Em tabagista, investigar neoplasia concomitante."},
    {"n":19,"topic":"Micoses pulmonares","difficulty":"difícil","statement":"Neutropênico após quimioterapia apresenta febre, hemoptise e nódulos com halo em vidro fosco. Qual alternativa diferencia corretamente as formas de aspergilose?","correct":"D","alts":[{"l":"A","t":"É aspergiloma; toda forma é tratada com corticoide sistêmico.","e":"Incorreta. Halo em neutropênico sugere angioinvasão e corticoide agrava imunossupressão."},{"l":"B","t":"É ABPA; ocorre apenas em cavidades de tuberculose.","e":"Incorreta. ABPA é hipersensibilidade em asma/FC."},{"l":"C","t":"É aspergilose invasiva; tratamento de primeira linha é fluconazol.","e":"Incorreta. Fluconazol não cobre adequadamente Aspergillus."},{"l":"D","t":"É aspergilose invasiva, tratada com voriconazol/isavuconazol; aspergiloma coloniza cavidade e ABPA é hipersensibilidade tratada sobretudo com corticoide.","e":"Correta. Diferencia mecanismo, hospedeiro e tratamento das três entidades."}],"general":"Aspergilose invasiva é emergência em neutropenia. Voriconazol ou isavuconazol são opções de primeira linha; anfotericina B lipossomal é alternativa. Reverter neutropenia quando possível melhora prognóstico.","summary":"Invasiva invade vasos; aspergiloma coloniza; ABPA sensibiliza.","memory":"Halo + neutropenia = tratar Aspergillus invasivo cedo.","trap":"Não esperar cultura positiva se a suspeita clínica for alta."},
    {"n":23,"topic":"Tromboembolismo pulmonar","difficulty":"médio","statement":"Idoso no pós-operatório de fratura de fêmur tem dispneia súbita e hipoxemia, mas pressão preservada. Qual conduta é mais adequada?","correct":"B","alts":[{"l":"A","t":"Confirmar apenas com radiografia e trombolisar imediatamente.","e":"Incorreta. Radiografia não confirma TEP e trombólise não é rotina em estáveis."},{"l":"B","t":"Realizar angio-TC (ou V/Q se contraste contraindicado) e anticoagular; estratificar repercussão do VD.","e":"Correta. É a abordagem do TEP hemodinamicamente estável."},{"l":"C","t":"Solicitar espirometria e aguardar uma semana sem anticoagulação.","e":"Incorreta. Espirometria não confirma TEP agudo e atraso pode ser perigoso."},{"l":"D","t":"Usar antibiótico como tratamento definitivo.","e":"Incorreta. Antibiótico não trata tromboembolismo."}],"general":"Em estabilidade, a angio-TC confirma o diagnóstico e anticoagulação é a base. A escolha entre DOAC, HBPM e HNF considera rim, sangramento, cirurgia recente e necessidade de intervenção.","summary":"TEP estável: imagem confirmatória e anticoagulação.","memory":"Estável anticoagula; instável reperfunde.","trap":"Cirurgia recente aumenta o risco hemorrágico."},
    {"n":24,"topic":"Tromboembolismo pulmonar","difficulty":"difícil","statement":"Qual alternativa distingue corretamente probabilidade diagnóstica e prognóstico em suspeita de TEP com PESI baixo?","correct":"A","alts":[{"l":"A","t":"Wells orienta D-dímero/angio-TC; PESI estima mortalidade e elegibilidade a cuidado ambulatorial; TEP baixo risco pode receber DOAC se critérios permitirem.","e":"Correta. Probabilidade pré-teste e prognóstico são etapas diferentes."},{"l":"B","t":"PESI confirma TEP e dispensa imagem.","e":"Incorreta. PESI não é teste diagnóstico."},{"l":"C","t":"D-dímero positivo confirma TEP e obriga trombólise.","e":"Incorreta. D-dímero é sensível, pouco específico; trombólise depende de risco hemodinâmico."},{"l":"D","t":"Todo TEP com PESI baixo requer internação e varfarina.","e":"Incorreta. Casos selecionados podem ser tratados ambulatorialmente com DOAC."}],"general":"Em probabilidade baixa/intermediária, D-dímero negativo pode excluir TEP; positivo leva à imagem. PESI/sPESI ajuda a definir risco, mas alta ambulatorial também requer avaliação de sangramento, oxigenação, suporte e adesão.","summary":"Wells diagnostica; PESI prognostica.","memory":"Dímero exclui; angio-TC confirma; PESI estratifica.","trap":"Não chamar D-dímero de exame confirmatório."},
    {"n":25,"topic":"Tromboembolismo pulmonar","difficulty":"difícil","statement":"Paciente oncológico, taquicárdico e com hemoptise tem Wells compatível com TEP provável/intermediário. Qual estratégia é mais alinhada ao manejo atual?","correct":"C","alts":[{"l":"A","t":"Trombólise imediata apenas pela pontuação de Wells.","e":"Incorreta. Wells não indica reperfusão; ela depende de instabilidade e risco."},{"l":"B","t":"Aguardar D-dímero mesmo com alta probabilidade, sem anticoagular.","e":"Incorreta. Alta probabilidade direciona à imagem e pode justificar anticoagulação enquanto aguarda, se segura."},{"l":"C","t":"Angio-TC para confirmação, ultrassom/eco e biomarcadores conforme necessidade; anticoagulação, reservando trombólise para instabilidade ou resgate.","e":"Correta. Separa confirmação, estratificação e tratamento por risco."},{"l":"D","t":"Excluir TEP porque hemoptise sugere apenas infecção.","e":"Incorreta. Hemoptise integra o escore de Wells e pode ocorrer no TEP."}],"general":"HNF é útil quando pode haver procedimento/reperfusão ou se é desejada reversão rápida. No paciente estável com disfunção de VD, a regra é anticoagular e monitorar; trombólise de rotina aumenta sangramento.","summary":"Probabilidade indica exames; hemodinâmica indica reperfusão.","memory":"Wells não é botão de trombólise.","trap":"O gabarito histórico deve ser lido à luz da estratificação contemporânea."},
    {"n":26,"topic":"Tromboembolismo pulmonar","difficulty":"difícil","statement":"Paciente após artroplastia tem TEP bilateral, PA 82/58 e pré-síncope. Qual explicação e tratamento são corretos?","correct":"B","alts":[{"l":"A","t":"Choque distributivo por vasodilatação; tratar apenas com volume.","e":"Incorreta. O choque é obstrutivo e excesso de volume pode piorar o VD."},{"l":"B","t":"Pós-carga abrupta dilata e falha o VD, reduz enchimento do VE; anticoagular e realizar reperfusão urgente, ponderando trombólise versus embolectomia pelo sangramento cirúrgico.","e":"Correta. Integra a fisiopatologia e a complexidade do pós-operatório recente."},{"l":"C","t":"Falência primária do VE; indicar diurético e alta.","e":"Incorreta. A lesão inicial é a obstrução pulmonar com falência direita."},{"l":"D","t":"Broncoespasmo isolado; tratar com salbutamol.","e":"Incorreta. Não explica hipotensão e TEP confirmado."}],"general":"TEP de alto risco causa choque obstrutivo. HNF facilita manejo intervencionista; trombólise sistêmica é padrão se não contraindicada, e terapias por cateter/cirurgia são alternativas quando o risco hemorrágico é proibitivo ou há falha.","summary":"Falência do VD determina o choque no TEP maciço.","memory":"VD cheio, VE vazio.","trap":"Cirurgia recente pode favorecer reperfusão mecânica em vez de lise sistêmica."},
    {"n":27,"topic":"Tromboembolismo pulmonar","difficulty":"médio","statement":"Em TEP segmentar estável associado a anticoncepcional, qual plano agudo e tardio é o mais adequado?","correct":"D","alts":[{"l":"A","t":"Trombolisar e suspender anticoagulação após 48 horas.","e":"Incorreta. Não há instabilidade e o tratamento mínimo é muito mais longo."},{"l":"B","t":"Usar apenas AAS por tempo indefinido.","e":"Incorreta. AAS não substitui anticoagulação terapêutica inicial."},{"l":"C","t":"Anticoagular obrigatoriamente para sempre, sem avaliar o fator transitório.","e":"Incorreta. Estrogênio removível pode caracterizar fator transitório; duração deve ser individualizada."},{"l":"D","t":"Iniciar anticoagulação, suspender estrogênio e manter por pelo menos três meses; estender se risco persistente/recorrente superar sangramento.","e":"Correta. Resume fase aguda e decisão de duração."}],"general":"DOAC é opção em muitos estáveis. A duração depende de provocação transitória, câncer, recorrência, trombofilia, risco de sangramento e preferência. Deve-se orientar contracepção sem estrogênio.","summary":"Três meses é o tratamento mínimo usual do TEP.","memory":"Remova o gatilho e reavalie o risco aos três meses.","trap":"Não confundir contraceptivo como fator transitório com ausência de risco futuro."},
    {"n":28,"topic":"Tromboembolismo pulmonar","difficulty":"difícil","statement":"Paciente oncológica com TEP lobar bilateral está normotensa, mas teve quase síncope. Como o risco deve orientar o tratamento?","correct":"A","alts":[{"l":"A","t":"Anticoagular e avaliar PESI, troponina/BNP e VD; monitorar intensamente se risco intermediário-alto e reservar reperfusão para deterioração.","e":"Correta. A pressão preservada afasta alto risco imediato, mas VD/biomarcadores refinam o risco."},{"l":"B","t":"Trombolisar todo TEP bilateral independentemente da pressão.","e":"Incorreta. Extensão anatômica isolada não indica lise e aumenta risco hemorrágico."},{"l":"C","t":"Não tratar porque a pressão está normal.","e":"Incorreta. TEP confirmado requer anticoagulação, salvo contraindicação."},{"l":"D","t":"Tratar apenas com oxigênio e repetir TC em seis meses.","e":"Incorreta. Oxigênio é suporte e não impede progressão/recorrência."}],"general":"A obstrução eleva a pós-carga do VD e pode reduzir o débito mesmo antes da hipotensão. Disfunção do VD mais biomarcador positivo define grupo intermediário-alto que necessita vigilância próxima.","summary":"Normotensão não significa ausência de risco.","memory":"Pressão primeiro; depois VD e troponina.","trap":"Quase síncope é alerta, mas não substitui critérios objetivos."},
    {"n":32,"topic":"Insuficiência respiratória aguda","difficulty":"difícil","statement":"Em COVID-19 com PCR 180, D-dímero 800 e P/F 190, qual interpretação e orientação são mais corretas?","correct":"C","alts":[{"l":"A","t":"PCR confirma infecção bacteriana e D-dímero confirma TEP; trombolisar.","e":"Incorreta. Ambos são inespecíficos e exigem contexto clínico."},{"l":"B","t":"Os marcadores não têm relação com gravidade e a filha sintomática pode manter contatos sem precaução.","e":"Incorreta. Inflamação/coagulação associam-se à gravidade e transmissão exige medidas."},{"l":"C","t":"PCR reflete inflamação por citocinas; D-dímero reflete ativação coagulação/fibrinólise; esperar vidro fosco periférico e orientar máscara, testagem, redução de contato e sinais de alarme.","e":"Correta. Integra fisiopatologia, imagem e saúde pública sem superinterpretar marcadores."},{"l":"D","t":"Ferritina e linfopenia excluem COVID-19 e indicam apenas asma.","e":"Incorreta. Esses achados podem acompanhar COVID grave."}],"general":"Idade, obesidade, diabetes, doença cardiovascular/renal/pulmonar e imunossupressão aumentam risco. Protocolos de isolamento e antivirais mudam com o tempo e devem seguir orientação sanitária vigente.","summary":"COVID grave envolve inflamação, alveolite e imunotrombose.","memory":"PCR inflama; D-dímero alerta; TC mostra vidro fosco.","trap":"D-dímero isolado não confirma TEP nem define anticoagulação terapêutica."},
    {"n":33,"topic":"Insuficiência respiratória aguda","difficulty":"médio","statement":"DPOC exacerbado com pH 7,28, PaCO2 68, PaO2 54 e sonolência apresenta qual tipo de IRpA e suporte inicial?","correct":"B","alts":[{"l":"A","t":"IRpA tipo I pura; oxigênio livre até SatO2 100%.","e":"Incorreta. Há hipercapnia e hiperóxia pode agravar retenção de CO2."},{"l":"B","t":"IRpA tipo II hipercápnica; oxigênio alvo 88–92% e VNI se protege via aérea, com tratamento da exacerbação.","e":"Correta. VNI reduz trabalho respiratório e intubação na acidose hipercápnica."},{"l":"C","t":"SDRA grave; trombólise imediata.","e":"Incorreta. A gasometria e o contexto apontam exacerbação de DPOC."},{"l":"D","t":"Alcalose respiratória; nenhuma ventilação é necessária.","e":"Incorreta. O pH está baixo e o CO2 alto."}],"general":"Associar SABA/SAMA, corticoide sistêmico e antibiótico quando purulência/gravidade indicarem. Reavaliar clínica e gasometria cedo; incapacidade de proteger via aérea ou falha de VNI exige intubação.","summary":"Tipo II é hipercápnica e costuma responder à VNI na DPOC.","memory":"CO2 alto + pH baixo = VNI, se puder.","trap":"Sonolência progressiva pode contraindicar VNI."},
    {"n":34,"topic":"Insuficiência respiratória aguda","difficulty":"difícil","statement":"DPOC com pneumonia tem pH 7,27, PaCO2 53 e PaO2 120 sob Venturi 50%. Qual opção interpreta e trata corretamente?","correct":"D","alts":[{"l":"A","t":"Não há IRpA porque PaO2 é 120; retirar todo suporte.","e":"Incorreta. A PaO2 foi obtida sob FiO2 alta e há acidose hipercápnica."},{"l":"B","t":"Há apenas shunt, sem hipoventilação; aumentar FiO2 para 100%.","e":"Incorreta. PaCO2 elevado demonstra hipoventilação e hiperóxia deve ser evitada."},{"l":"C","t":"Há apenas hipoventilação; antibiótico não é necessário apesar da consolidação e febre.","e":"Incorreta. Pneumonia causa componente de baixa V/Q/shunt e requer tratamento."},{"l":"D","t":"Há baixa V/Q/shunt pela pneumonia e hipoventilação pela DPOC; titular O2 a 88–92%, iniciar VNI se possível e tratar com broncodilatador, corticoide e antibiótico.","e":"Correta. Reconhece mecanismo misto e aborda ventilação e causa."}],"general":"A relação P/F aproximada é 240, mas coexistem hipercapnia e acidemia. A resposta à VNI deve ser monitorada; rebaixamento, instabilidade ou piora gasométrica indicam intubação.","summary":"Pneumonia altera V/Q; DPOC causa hipoventilação.","memory":"PaO2 alta sob FiO2 alta não significa pulmão normal.","trap":"Sempre interpretar oxigenação junto da FiO2."}
  ]$data$::jsonb) AS x(n int,topic text,difficulty text,statement text,correct text,alts jsonb,general text,summary text,memory text,trap text)
  LOOP
    q_id := pg_temp.p3_uuid('pneumologia-p3-aberta-objetivada-'||r.n);
    SELECT id INTO t_id FROM public.topics WHERE discipline_id=d_id AND name=r.topic LIMIT 1;
    IF t_id IS NULL THEN
      INSERT INTO public.topics(discipline_id,name) VALUES(d_id,r.topic) RETURNING id INTO t_id;
    END IF;
    INSERT INTO public.questions(id,discipline_id,topic_id,difficulty,statement,question_type,correct_answer,correct_answers,general_comment,summary,memory_tip,trap,reference,active,exam,image_url)
    VALUES(q_id,d_id,t_id,r.difficulty,r.statement,'single',r.correct,ARRAY[r.correct],r.general,r.summary,r.memory,r.trap,
      'Prova 3 de Pneumologia — questão aberta convertida em objetiva e revisada no padrão MedQuiz.',true,'P3',NULL)
    ON CONFLICT(id) DO UPDATE SET topic_id=EXCLUDED.topic_id,statement=EXCLUDED.statement,question_type='single',
      correct_answer=EXCLUDED.correct_answer,correct_answers=EXCLUDED.correct_answers,
      general_comment=EXCLUDED.general_comment,summary=EXCLUDED.summary,memory_tip=EXCLUDED.memory_tip,
      trap=EXCLUDED.trap,reference=EXCLUDED.reference,active=true,exam='P3';

    FOR a IN SELECT value FROM jsonb_array_elements(r.alts)
    LOOP
      INSERT INTO public.alternatives(id,question_id,letter,text,explanation)
      VALUES(pg_temp.p3_uuid(q_id::text||(a->>'l')),q_id,a->>'l',a->>'t',a->>'e')
      ON CONFLICT(question_id,letter) DO UPDATE SET text=EXCLUDED.text,explanation=EXCLUDED.explanation;
    END LOOP;
  END LOOP;
END $$;

COMMIT;

SELECT count(*) AS total_abertas_objetivadas_p3
FROM public.questions q JOIN public.disciplines d ON d.id=q.discipline_id
WHERE d.name='Pneumologia' AND q.exam='P3' AND q.id IN
  (SELECT pg_temp.p3_uuid('pneumologia-p3-aberta-objetivada-'||n) FROM generate_series(1,34) n);
