-- Primeiro lote deduplicado da monitoria/questões antigas de Gastro P3.
-- Enunciados anacrônicos foram ajustados sem alterar a competência avaliada.
BEGIN;

CREATE OR REPLACE FUNCTION pg_temp.gastro_mon1_uuid(seed text) RETURNS uuid
LANGUAGE sql IMMUTABLE AS $$
  SELECT (substr(md5(seed),1,8)||'-'||substr(md5(seed),9,4)||'-5'||substr(md5(seed),14,3)||'-a'||substr(md5(seed),18,3)||'-'||substr(md5(seed),21,12))::uuid
$$;

DO $$
DECLARE
  v_discipline_id uuid;
  v_topic_id uuid;
  v_question_id uuid;
  q record;
  a jsonb;
BEGIN
  SELECT id INTO v_discipline_id FROM public.disciplines
  WHERE slug='gastroenterologia' LIMIT 1;
  IF v_discipline_id IS NULL THEN RAISE EXCEPTION 'Disciplina Gastroenterologia não encontrada'; END IF;

  FOR q IN SELECT * FROM jsonb_to_recordset($data$[
    {"k":"mon-reto-idoso","topic":"Câncer colorretal","d":"médio","s":"Homem de 79 anos apresenta evacuações frequentes em pequeno volume, muco, sangue, dor retal e perda ponderal. Qual combinação melhor descreve a abordagem inicial, a principal hipótese e o tratamento geral?","c":"A","g":"Sintomas distais sugerem neoplasia de reto. Exame proctológico e colonoscopia com biópsia confirmam; tratamento depende do estadiamento e pode combinar terapia neoadjuvante e cirurgia.","sum":"Tenesmo, sangue e dor retal exigem toque/proctoscopia e colonoscopia.","mem":"Reto dá urgência, tenesmo e pequeno volume.","trap":"Cirurgia transanal serve apenas para tumores iniciais criteriosamente selecionados.","alts":[["A","Exame proctológico e colonoscopia com biópsia — neoplasia de reto — tratamento definido pelo estadiamento, frequentemente com cirurgia e terapia oncológica","Correta. Integra diagnóstico anatômico, confirmação histológica e tratamento por estágio."],["B","Coprocultura — gastroenterite — antibiótico empírico prolongado","Incorreta. Um ano de sintomas, sangue e perda ponderal são sinais de neoplasia."],["C","Retoscopia isolada — neoplasia de sigmoide — radioterapia exclusiva","Incorreta. É necessário examinar todo o cólon e obter histologia; radioterapia isolada não é regra."],["D","Toque retal — câncer de próstata — prostatectomia","Incorreta. O padrão intestinal e o sangramento apontam para origem colorretal."],["E","Pesquisa de sangue oculto — SII — antiespasmódico","Incorreta. Sangramento visível e perda de peso afastam manejo como SII."]]},
    {"k":"mon-sii-triciclico","topic":"Síndrome do intestino irritável","d":"médio","s":"Sobre o tratamento da síndrome do intestino irritável, assinale a alternativa incorreta.","c":"A","g":"Tricíclicos podem beneficiar dor e SII com diarreia, mas seus efeitos anticolinérgicos tendem a piorar constipação.","sum":"TCA desacelera trânsito; use com cautela ou evite na SII-C.","mem":"Tricíclico trava o intestino.","trap":"Tratamento é orientado pelo sintoma predominante, não por uma lista fixa.","alts":[["A","Antidepressivos tricíclicos são preferenciais na SII com constipação","Correta como incorreta. Podem agravar obstipação."],["B","Antiespasmódicos exigem cautela quando predomina constipação","Incorreta como resposta. Efeitos anticolinérgicos podem piorar trânsito."],["C","Antidiarreicos não tratam o subtipo constipado","Incorreta como resposta. Loperamida não tem indicação para constipação."],["D","Terapias cérebro-intestino podem ajudar pacientes selecionados","Incorreta como resposta. Há benefício para sintomas globais em alguns casos."],["E","A escolha terapêutica deve considerar o subtipo e os sintomas dominantes","Incorreta como resposta. Esse é o princípio correto."]]},
    {"k":"mon-pcr-tempo","topic":"Pancreatite aguda","d":"médio","s":"Na pancreatite aguda, qual marcador inflamatório tende a subir mais lentamente e alcançar maior utilidade prognóstica após aproximadamente 48–72 horas?","c":"C","g":"PCR é marcador de fase aguda tardio; valores elevados após 48 horas se associam a inflamação grave, mas têm utilidade limitada na admissão imediata.","sum":"PCR demora; amilase e lipase ajudam no diagnóstico, não na gravidade.","mem":"PCR precisa de dois dias.","trap":"O valor absoluto de amilase/lipase não acompanha a gravidade.","alts":[["A","Amilase sérica","Incorreta. Eleva-se cedo e pode normalizar em poucos dias."],["B","Lipase sérica","Incorreta. Permanece elevada por mais tempo, porém não é o marcador inflamatório tardio descrito."],["C","Proteína C-reativa","Correta. Sua elevação máxima costuma ocorrer após 48–72 horas."],["D","Troponina","Incorreta. É marcador de lesão miocárdica."],["E","Bilirrubina indireta","Incorreta. Não tem esse papel prognóstico."]]},
    {"k":"mon-pancreatite-enzimas-evolucao","topic":"Pancreatite aguda","d":"médio","s":"Assinale a afirmação incorreta sobre pancreatite aguda.","c":"D","g":"A queda de enzimas não é marcador confiável de resolução; evolução é acompanhada clinicamente, por função orgânica e complicações.","sum":"Enzima diagnostica, mas não gradua nem acompanha gravidade.","mem":"Amilase não é termômetro de gravidade.","trap":"TC precoce não é necessária quando diagnóstico é claro e evolução favorável.","alts":[["A","Litíase biliar é uma das etiologias mais frequentes","Incorreta como resposta. A afirmação é verdadeira."],["B","PCR após 48 horas pode contribuir para avaliação prognóstica","Incorreta como resposta. A afirmação é verdadeira."],["C","TC tem valor para detectar necrose e complicações em contexto apropriado","Incorreta como resposta. A afirmação é verdadeira."],["D","A diminuição de amilase e lipase comprova boa evolução clínica","Correta como incorreta. A cinética enzimática não determina prognóstico."],["E","Antibiótico não deve ser usado rotineiramente na necrose estéril","Incorreta como resposta. A afirmação é verdadeira."]]},
    {"k":"mon-crc-toque-retal","topic":"Câncer colorretal","d":"médio","s":"A respeito da avaliação inicial do câncer colorretal, assinale a alternativa correta.","c":"B","g":"Sangramento anal exige avaliação anorretal, incluindo toque, mas colonoscopia com biópsia é necessária para diagnóstico e pesquisa de lesões sincrônicas.","sum":"Toque alcança reto baixo; colonoscopia confirma e examina o cólon.","mem":"Sangrou: olhe e toque; suspeitou: colonoscopia.","trap":"Hemograma detecta repercussão, não diagnostica o tumor.","alts":[["A","Sangue oculto é exame confirmatório em paciente com sangramento visível","Incorreta. Não se usa rastreio para confirmar sintoma já manifesto."],["B","Paciente com sangramento anal deve realizar exame proctológico e toque retal, pois tumor de reto baixo pode ser palpável","Correta. O exame simples pode localizar lesão distal e não deve ser omitido."],["C","Hemograma é o primeiro e único exame diagnóstico","Incorreta. Avalia anemia, mas não confirma neoplasia."],["D","Enema opaco é o método padrão para estadiamento sistêmico","Incorreta. O estadiamento usa TC e, no reto, RM pélvica, entre outros."],["E","CEA normal exclui câncer colorretal","Incorreta. CEA não tem sensibilidade para excluir diagnóstico."]]},
    {"k":"mon-crc-risco-rcu","topic":"Câncer colorretal","d":"fácil","s":"Qual condição é fator importante de risco para adenocarcinoma do cólon?","c":"B","g":"Colite ulcerativa extensa e duradoura aumenta risco de neoplasia colorretal, especialmente com inflamação cumulativa e colangite esclerosante primária.","sum":"Colite extensa e longa aumenta o risco.","mem":"Inflamação crônica pode virar displasia.","trap":"Doença diverticular não é lesão precursora de câncer.","alts":[["A","Doença diverticular não complicada","Incorreta. Não é considerada condição precursora direta."],["B","Retocolite ulcerativa extensa e de longa duração","Correta. Aumenta risco de displasia e câncer."],["C","Infecção autolimitada por Yersinia","Incorreta. Não é fator clássico de risco oncológico crônico."],["D","Dieta rica em fibras","Incorreta. Não aumenta o risco."],["E","Hemorroidas internas","Incorreta. Podem sangrar, mas não causam câncer."]]},
    {"k":"mon-necrose-step-up","topic":"Pancreatite aguda","d":"difícil","s":"Paciente com pancreatite aguda apresenta 50% de necrose pancreática no quarto dia. Sobre intervenção na necrose, assinale a alternativa incorreta.","c":"C","g":"Na ausência de indicação emergencial, intervenção é adiada até a coleção organizar; necrose infectada sintomática é tratada por estratégia step-up minimamente invasiva.","sum":"Necrose precoce: suporte; infectada organizada: drene e escale.","mem":"Espere formar parede quando puder.","trap":"Percentual de necrose isolado não indica laparotomia precoce.","alts":[["A","Falência orgânica persistente por mais de 48 horas define pancreatite grave","Incorreta como resposta. É definição da classificação de Atlanta revisada."],["B","Falência orgânica precoce persistente associa alta mortalidade","Incorreta como resposta. É verdadeiro."],["C","A presença de 50% de necrose indica laparotomia precoce obrigatória para desbridamento","Correta como incorreta. A cirurgia precoce aumenta morbimortalidade e não é indicada apenas pela extensão."],["D","Na necrose infectada sintomática, drenagem e técnicas minimamente invasivas são preferidas inicialmente","Incorreta como resposta. É o conceito step-up."],["E","Em pancreatite biliar grave com coleções, colecistectomia costuma ser adiada até controle do processo local","Incorreta como resposta. Evita operar durante inflamação intensa."]]},
    {"k":"mon-apendicite-classica","topic":"Abdome agudo","d":"médio","s":"Adolescente de 14 anos apresenta dor periumbilical que migrou para fossa ilíaca direita, febre, vômitos, anorexia e irritação peritoneal localizada. Qual conduta é mais adequada?","c":"C","g":"Em apresentação altamente típica com peritonismo localizado, avaliação cirúrgica urgente é mandatória; imagem é reservada conforme incerteza e contexto.","sum":"Migração da dor + peritonismo = avaliação cirúrgica urgente.","mem":"Apendicite caminha do umbigo à FID.","trap":"Imagem não deve atrasar cirurgia em quadro clássico complicado.","alts":[["A","Exames de imagem são sempre obrigatórios antes de qualquer decisão","Incorreta. Podem ajudar em casos duvidosos, mas não são universais."],["B","Tratamento exclusivamente clínico é obrigatório","Incorreta. O quadro clássico com irritação peritoneal requer abordagem cirúrgica."],["C","Encaminhar para avaliação cirúrgica urgente, com apendicectomia preferencialmente laparoscópica","Correta. É a conduta compatível com o caso."],["D","Fístula entérica é a complicação pós-operatória mais comum","Incorreta. Infecção de sítio cirúrgico é mais comum."],["E","A incisão mediana é obrigatória em toda apendicite aberta","Incorreta. Incisões localizadas são usuais em casos não difusos."]]},
    {"k":"mon-crc-ceco-cirurgia","topic":"Câncer colorretal","d":"fácil","s":"Quanto ao tratamento cirúrgico do câncer colorretal, assinale a alternativa correta.","c":"C","g":"Tumores do ceco são tratados por hemicolectomia direita oncológica, com ligadura vascular e linfadenectomia adequadas.","sum":"Ceco pertence ao território da colectomia direita.","mem":"Ceco à direita, hemicolectomia direita.","trap":"Metástase ou invasão de órgão adjacente não torna automaticamente o tumor inoperável.","alts":[["A","Fístula duodenocólica contraindica qualquer ressecção","Incorreta. Ressecção multivisceral pode ser considerada se R0 for possível."],["B","Metástase hepática contraindica via laparoscópica e intenção curativa em todos os casos","Incorreta. Casos selecionados podem ter tratamento curativo."],["C","Tumor do ceco é tratado adequadamente com hemicolectomia direita oncológica","Correta. Resseca o segmento e a drenagem linfovascular correspondente."],["D","Invasão uterina exige sempre exenteração pélvica anterior completa","Incorreta. A extensão da ressecção depende dos órgãos envolvidos e possibilidade de margens."],["E","Ooforectomia profilática é obrigatória para toda paciente","Incorreta. Não é recomendação universal."]]},
    {"k":"mon-sii-crc-sintoma-comum","topic":"Síndrome do intestino irritável","d":"fácil","s":"Qual sintoma pode ocorrer tanto em síndrome do intestino irritável quanto em câncer de cólon, embora sinais de alarme exijam investigação?","c":"D","g":"Mudança do hábito intestinal pode ocorrer em ambas; sangramento, anemia, perda ponderal e sintomas noturnos favorecem doença orgânica.","sum":"Alteração do hábito é inespecífica; alarme diferencia.","mem":"Alternância pode ser funcional ou orgânica.","trap":"Não atribua nova mudança do hábito em idoso automaticamente à SII.","alts":[["A","Hematoquezia recorrente","Incorreta. Não é explicada por SII e exige investigação."],["B","Dor que desperta frequentemente à noite","Incorreta. É sinal de alarme orgânico."],["C","Perda ponderal involuntária","Incorreta. Não é característica de SII."],["D","Alternância entre constipação e diarreia","Correta. Pode ocorrer em ambos os contextos."],["E","Anemia ferropriva","Incorreta. Sugere perda ou má absorção orgânica."]]},
    {"k":"mon-crohn-fistula-perianal","topic":"Doença de Crohn","d":"fácil","s":"Homem de 42 anos apresenta dor abdominal, febre baixa, diarreia sanguinolenta, perda ponderal, abscesso perianal e fístula retal. Qual diagnóstico é mais provável?","c":"E","g":"Doença perianal fistulizante é manifestação típica de Crohn transmural e pode preceder outros achados intestinais.","sum":"Fístula perianal + diarreia inflamatória = Crohn.","mem":"Crohn atravessa a parede e cria fístulas.","trap":"RCU limita-se à mucosa e raramente produz fístula perianal verdadeira.","alts":[["A","Tuberculose intestinal","Incorreta. Pode mimetizar ileíte, mas o conjunto favorece Crohn."],["B","Doença diverticular","Incorreta. Idade e padrão perianal não são típicos."],["C","Retocolite ulcerativa","Incorreta. Fístulas são incomuns por inflamação não transmural."],["D","Síndrome do intestino irritável","Incorreta. Não causa febre, sangue, perda de peso ou fístula."],["E","Doença de Crohn","Correta. Explica inflamação intestinal e doença perianal penetrante."]]},
    {"k":"mon-crohn-colite-indeterminada","topic":"Doença de Crohn","d":"médio","s":"Sobre manifestações e diagnóstico diferencial da doença de Crohn, assinale a alternativa incorreta.","c":"C","g":"Colite não classificada existe, mas não corresponde a 80% dos casos após investigação moderna.","sum":"Crohn imita apendicite, RCU e enterocolites, mas a maioria pode ser classificada.","mem":"Colite indeterminada é minoria.","trap":"O termo é usado com rigor, especialmente em peças cirúrgicas.","alts":[["A","Ileíte aguda pode exigir diferenciação de apendicite","Incorreta como resposta. É verdadeiro."],["B","Colite de Crohn pode ser difícil de diferenciar da RCU","Incorreta como resposta. É verdadeiro."],["C","Em até 80% dos casos nenhum método permite classificação, sendo a maioria colite indeterminada","Correta como incorreta. Essa frequência é grosseiramente excessiva."],["D","Enterocolites infecciosas, isquêmicas e medicamentosas entram no diferencial","Incorreta como resposta. É verdadeiro."],["E","O diagnóstico integra endoscopia, histologia e imagem","Incorreta como resposta. É verdadeiro."]]},
    {"k":"mon-rcu-complicacao-exceto","topic":"Retocolite ulcerativa","d":"fácil","s":"São complicações possíveis da retocolite ulcerativa, exceto:","c":"C","g":"RCU pode causar hemorragia, colite fulminante, megacólon tóxico, displasia e câncer; estenose ileal não é complicação típica.","sum":"RCU é colônica; estenose ileal aponta para Crohn ou outra causa.","mem":"Íleo estenosado não combina com RCU clássica.","trap":"Backwash ileitis não equivale a estenose transmural.","alts":[["A","Megacólon tóxico","Incorreta como resposta. É complicação grave reconhecida."],["B","Hemorragia digestiva baixa grave","Incorreta como resposta. Pode ocorrer."],["C","Estenose ileal fibrótica","Correta como exceção. Não é complicação típica da RCU."],["D","Displasia e câncer colorretal","Incorreta como resposta. O risco aumenta com colite extensa e longa."],["E","Colite fulminante","Incorreta como resposta. É apresentação grave possível."]]},
    {"k":"mon-rcu-pancolite","topic":"Retocolite ulcerativa","d":"médio","s":"Homem de 28 anos apresenta dez evacuações sanguinolentas diárias, tenesmo, sintomas noturnos, anemia, VHS elevada e colonoscopia com inflamação contínua do reto ao ceco, friabilidade e ulcerações superficiais. Qual o diagnóstico mais provável?","c":"D","g":"A distribuição contínua desde o reto, sintomas sanguinolentos e abscessos de cripta favorecem pancolite ulcerativa.","sum":"Contínua do reto ao ceco = pancolite ulcerativa.","mem":"RCU começa no reto e sobe sem saltos.","trap":"Crohn costuma ser segmentar e pode poupar o reto.","alts":[["A","Doença celíaca","Incorreta. Não causa colite contínua sanguinolenta."],["B","Doença de Crohn","Incorreta. A distribuição e profundidade descritas favorecem RCU."],["C","Colite pseudomembranosa","Incorreta. Faltam exposição e pseudomembranas; padrão crônico favorece DII."],["D","Retocolite ulcerativa extensa","Correta. Explica clínica, endoscopia e histologia."],["E","Síndrome do intestino irritável","Incorreta. Não produz anemia ou inflamação endoscópica."]]},
    {"k":"mon-crc-colon-direito","topic":"Câncer colorretal","d":"fácil","s":"Paciente apresenta fadiga, anemia ferropriva e emagrecimento, sem sintomas obstrutivos marcantes. Qual localização de câncer colorretal é mais provável?","c":"E","g":"Tumores do cólon direito frequentemente sangram de forma oculta e causam anemia; tumores esquerdos tendem a alterar calibre e obstruir.","sum":"Direito sangra oculto; esquerdo obstrui.","mem":"Direita = deficiência de ferro.","trap":"Ausência de sangue visível não exclui perda crônica.","alts":[["A","Cólon transverso","Incorreta. É possível, mas menos típico que cólon direito."],["B","Cólon descendente","Incorreta. Tende a produzir alteração do hábito e obstrução."],["C","Reto","Incorreta. Sangramento visível e tenesmo são mais comuns."],["D","Sigmoide","Incorreta. Costuma causar sintomas de estreitamento luminal."],["E","Cólon direito","Correta. Sangramento oculto crônico explica anemia e fadiga."]]},
    {"k":"mon-sii-sinal-contra","topic":"Síndrome do intestino irritável","d":"fácil","s":"Em paciente com diarreia crônica, qual sintoma fala contra síndrome do intestino irritável e exige investigação de doença orgânica?","c":"B","g":"Diarreia que desperta do sono é sinal de alarme; SII tipicamente ocorre durante vigília e relaciona-se a refeições/estresse.","sum":"Diarreia noturna não é SII até prova em contrário.","mem":"Se acorda para evacuar, investigue.","trap":"Muco claro isolado pode ocorrer na SII.","alts":[["A","Piora após refeições","Incorreta. Reflexo gastrocólico exacerbado é comum na SII."],["B","Diarreia noturna que interrompe o sono","Correta. Favorece mecanismo orgânico ou secretor."],["C","Muco transparente nas fezes","Incorreta. Pode ocorrer sem inflamação."],["D","Cólicas abdominais recorrentes","Incorreta. É manifestação central da SII."],["E","Piora com estresse","Incorreta. É frequente pela interação cérebro-intestino."]]},
    {"k":"mon-malabsorcao-manifestacoes","topic":"Síndromes disabsortivas","d":"médio","s":"Em relação às manifestações das síndromes disabsortivas, assinale a alternativa correta.","c":"E","g":"Má absorção pode causar anemia, osteomalácia, hipoalbuminemia e deficiências de vitaminas A, D, E e K; supercrescimento bacteriano desconjuga sais biliares.","sum":"Má absorção afeta sangue, osso, proteína, nervos, visão e coagulação.","mem":"ADEK: visão, osso, nervo e sangue.","trap":"Manifestações dependem do nutriente e do segmento comprometido.","alts":[["A","Anemia, osteomalácia e hipoalbuminemia podem ocorrer","Incorreta isoladamente como melhor resposta; a afirmação é verdadeira, mas há opção mais abrangente."],["B","Supercrescimento bacteriano pode desconjugar sais biliares","Incorreta isoladamente como melhor resposta; a afirmação é verdadeira."],["C","Cegueira noturna, neuropatia e sangramento podem refletir deficiências vitamínicas","Incorreta isoladamente como melhor resposta; a afirmação é verdadeira."],["D","Somente A e B estão corretas","Incorreta. C também está correta."],["E","Todas as três afirmações estão corretas","Correta. Todas descrevem mecanismos ou repercussões reconhecidas."]]},
    {"k":"mon-sii-quadro-classico","topic":"Síndrome do intestino irritável","d":"fácil","s":"Pirose, náuseas, dor abdominal em cólica, distensão e diarreia diurna em pequenos volumes, pior após alimentação ou estresse e aliviada após evacuação, caracterizam principalmente:","c":"A","g":"O padrão flutuante, relação com estresse/refeições e alívio após evacuação sem sinais de alarme é compatível com SII.","sum":"Dor relacionada à evacuação e hábito alterado sugerem SII.","mem":"Come, estressa, dói; evacua, alivia.","trap":"Fibromialgia e outros transtornos somáticos podem coexistir.","alts":[["A","Síndrome do intestino irritável","Correta. É um padrão típico de interação cérebro-intestino."],["B","Doença diverticular complicada","Incorreta. Esperar-se-iam sinais inflamatórios localizados."],["C","Parasitose invasiva","Incorreta. Não é sugerida pela relação consistente com estresse e alívio."],["D","Pancreatite aguda","Incorreta. Seria dor intensa persistente com quadro sistêmico."],["E","Obstrução intestinal mecânica","Incorreta. Não explica curso crônico flutuante."]]},
    {"k":"mon-pc-dor-cirurgia","topic":"Pancreatite crônica","d":"difícil","s":"Sobre o tratamento da dor na pancreatite crônica, avalie: I. Cirurgia pode ser indicada quando a dor incapacitante persiste apesar de abstinência e analgesia. II. Em ducto principal dilatado, uma drenagem longitudinal pancreatojejunal pode ser apropriada. III. Esfincteroplastia biliar trata ducto pancreático fino. IV. Bloqueio do plexo celíaco é tratamento definitivo de escolha após qualquer falha analgésica. Quais estão corretas?","c":"A","g":"Dor refratária com ducto dilatado pode beneficiar drenagem cirúrgica; esfincteroplastia biliar não corrige ducto fino e bloqueio celíaco tem benefício variável e geralmente temporário.","sum":"Ducto grande drena; ducto pequeno exige outra estratégia.","mem":"Ducto dilatado permite ponte para o jejuno.","trap":"Bloqueio celíaco não é solução definitiva universal.","alts":[["A","Somente I e II","Correta. Ambas refletem indicações e princípios cirúrgicos aceitos."],["B","Somente I e IV","Incorreta. IV é excessiva e não corresponde a tratamento definitivo de escolha."],["C","Somente III e IV","Incorreta. Ambas estão erradas."],["D","I, II e III","Incorreta. III confunde vias biliar e pancreática."],["E","II, III e IV","Incorreta. III e IV estão erradas."]]},
    {"k":"mon-pc-esteatorreia-tardia","topic":"Pancreatite crônica","d":"médio","s":"Em relação à insuficiência pancreática na pancreatite crônica, assinale a alternativa correta.","c":"A","g":"Grande reserva funcional faz a esteatorreia surgir tardiamente, após perda de aproximadamente 90% da secreção exócrina.","sum":"Esteatorreia é manifestação tardia de insuficiência exócrina grave.","mem":"O pâncreas perde nove décimos antes da gordura aparecer.","trap":"Diabetes pancreatogênico tem risco de hipoglicemia e cetoacidose é menos comum.","alts":[["A","Esteatorreia costuma surgir quando a função exócrina cai para menos de cerca de 10% do normal","Correta. Há ampla reserva secretória."],["B","Má absorção é sempre a principal causa de emagrecimento desde o início","Incorreta. Dor, redução da ingestão e álcool também contribuem; esteatorreia é tardia."],["C","Icterícia decorre de maior reabsorção intestinal de sais biliares","Incorreta. Pode ocorrer por compressão/estenose biliar."],["D","Cegueira noturna e sangramento são universais","Incorreta. Deficiências podem ocorrer, mas não são universais."],["E","Diabetes está presente em 65% já no diagnóstico e geralmente causa cetoacidose","Incorreta. Frequência varia e cetoacidose é menos típica."]]}
  ]$data$::jsonb) AS x(k text,topic text,d text,s text,c text,g text,sum text,mem text,trap text,alts jsonb)
  LOOP
    SELECT id INTO v_topic_id FROM public.topics WHERE discipline_id=v_discipline_id AND name=q.topic LIMIT 1;
    IF v_topic_id IS NULL THEN
      v_topic_id:=pg_temp.gastro_mon1_uuid('gastro-topic-'||q.topic);
      INSERT INTO public.topics(id,discipline_id,name) VALUES(v_topic_id,v_discipline_id,q.topic)
      ON CONFLICT(id) DO UPDATE SET name=EXCLUDED.name;
    END IF;
    v_question_id:=pg_temp.gastro_mon1_uuid('gastro-p3-'||q.k);
    INSERT INTO public.questions(id,discipline_id,topic_id,exam,difficulty,statement,question_type,correct_answer,correct_answers,general_comment,summary,memory_tip,trap,reference,active,image_url)
    VALUES(v_question_id,v_discipline_id,v_topic_id,'P3',q.d,q.s,'single',q.c,ARRAY[q.c],q.g,q.sum,q.mem,q.trap,'Prova 3 de Gastroenterologia — payload deduplicado e revisado em 2026.',true,NULL)
    ON CONFLICT(id) DO UPDATE SET topic_id=EXCLUDED.topic_id,exam='P3',difficulty=EXCLUDED.difficulty,statement=EXCLUDED.statement,question_type='single',correct_answer=EXCLUDED.correct_answer,correct_answers=EXCLUDED.correct_answers,general_comment=EXCLUDED.general_comment,summary=EXCLUDED.summary,memory_tip=EXCLUDED.memory_tip,trap=EXCLUDED.trap,reference=EXCLUDED.reference,active=true,image_url=NULL;
    DELETE FROM public.alternatives WHERE question_id=v_question_id;
    FOR a IN SELECT value FROM jsonb_array_elements(q.alts) LOOP
      INSERT INTO public.alternatives(id,question_id,letter,text,explanation)
      VALUES(pg_temp.gastro_mon1_uuid(v_question_id::text||(a->>0)),v_question_id,a->>0,a->>1,a->>2);
    END LOOP;
  END LOOP;
END $$;

DO $$
DECLARE v_count integer; v_blank integer;
BEGIN
  SELECT count(*) INTO v_count FROM public.questions
  WHERE id IN (SELECT pg_temp.gastro_mon1_uuid('gastro-p3-'||key) FROM unnest(ARRAY[
    'mon-reto-idoso','mon-sii-triciclico','mon-pcr-tempo','mon-pancreatite-enzimas-evolucao',
    'mon-crc-toque-retal','mon-crc-risco-rcu','mon-necrose-step-up','mon-apendicite-classica',
    'mon-crc-ceco-cirurgia','mon-sii-crc-sintoma-comum','mon-crohn-fistula-perianal',
    'mon-crohn-colite-indeterminada','mon-rcu-complicacao-exceto','mon-rcu-pancolite',
    'mon-crc-colon-direito','mon-sii-sinal-contra','mon-malabsorcao-manifestacoes',
    'mon-sii-quadro-classico','mon-pc-dor-cirurgia','mon-pc-esteatorreia-tardia'
  ]) AS keys(key));
  SELECT count(*) INTO v_blank FROM public.alternatives a JOIN public.questions q ON q.id=a.question_id
  WHERE q.id IN (SELECT pg_temp.gastro_mon1_uuid('gastro-p3-'||key) FROM unnest(ARRAY[
    'mon-reto-idoso','mon-sii-triciclico','mon-pcr-tempo','mon-pancreatite-enzimas-evolucao',
    'mon-crc-toque-retal','mon-crc-risco-rcu','mon-necrose-step-up','mon-apendicite-classica',
    'mon-crc-ceco-cirurgia','mon-sii-crc-sintoma-comum','mon-crohn-fistula-perianal',
    'mon-crohn-colite-indeterminada','mon-rcu-complicacao-exceto','mon-rcu-pancolite',
    'mon-crc-colon-direito','mon-sii-sinal-contra','mon-malabsorcao-manifestacoes',
    'mon-sii-quadro-classico','mon-pc-dor-cirurgia','mon-pc-esteatorreia-tardia'
  ]) AS keys(key)) AND (coalesce(trim(a.text),'')='' OR coalesce(trim(a.explanation),'')='');
  IF v_count<>20 OR v_blank<>0 THEN RAISE EXCEPTION 'Auditoria monitoria 1 falhou: questões=%, vazias=%',v_count,v_blank; END IF;
END $$;

COMMIT;
