-- Complementos encontrados na conferência final das turmas 108, 115 e 118.
BEGIN;
CREATE OR REPLACE FUNCTION pg_temp.gastro_comp_uuid(seed text) RETURNS uuid LANGUAGE sql IMMUTABLE AS $$ SELECT (substr(md5(seed),1,8)||'-'||substr(md5(seed),9,4)||'-5'||substr(md5(seed),14,3)||'-a'||substr(md5(seed),18,3)||'-'||substr(md5(seed),21,12))::uuid $$;
DO $$
DECLARE v_discipline_id uuid; v_topic_id uuid; v_question_id uuid; q record; a jsonb;
BEGIN
 SELECT id INTO v_discipline_id FROM public.disciplines WHERE slug='gastroenterologia' LIMIT 1;
 FOR q IN SELECT * FROM jsonb_to_recordset($data$[
  {"k":"comp-disabsorcao-exame-menos-util","topic":"Síndromes disabsortivas","d":"médio","type":"single","s":"Jovem com diarreia crônica, esteatorreia, distensão e perda ponderal será investigado por síndrome disabsortiva. Qual exame tende a ser menos útil na avaliação etiológica inicial, na ausência de sinais colônicos?","c":["D"],"g":"Sorologia celíaca, biópsias duodenais, avaliação fecal, hemograma e parasitológico investigam causas prováveis; colonoscopia tem menor rendimento sem sinais de doença colônica.","sum":"Esteatorreia aponta primeiro para delgado e pâncreas.","mem":"Gordura nas fezes olha duodeno antes do cólon.","trap":"Colonoscopia passa a ser indicada se houver sangue, calprotectina elevada, idade de rastreio ou alarme.","alts":[["A","Endoscopia alta com biópsias duodenais","Incorreta como resposta. Avalia doença celíaca e mucosa."],["B","Anti-transglutaminase IgA e IgA total","Incorreta como resposta. Rastreia doença celíaca."],["C","Avaliação de gordura/coprologia fecal","Incorreta como resposta. Documenta má digestão/absorção."],["D","Colonoscopia sem indicação colônica adicional","Correta. É a menos direcionada ao quadro descrito."],["E","Hemograma e parasitológico de fezes","Incorreta como resposta. Avaliam repercussão e parasitoses."]]},
  {"k":"comp-lynch-cirurgia","topic":"Câncer colorretal","d":"difícil","type":"single","s":"Homem de 45 anos com síndrome de Lynch provável apresenta adenocarcinoma de ceco e linfonodos regionais comprometidos, sem metástases. Qual estratégia é mais apropriada?","c":["C"],"g":"Em Lynch, colectomia estendida reduz câncer metacrônico e deve ser discutida conforme idade e função; doença linfonodal indica quimioterapia adjuvante após ressecção oncológica.","sum":"Lynch jovem + N positivo: ressecção oncológica ampliada discutida e quimioterapia.","mem":"Lynch volta no cólon restante.","trap":"Radioterapia não é rotina para câncer de cólon direito.","alts":[["A","Hemicolectomia direita sem discutir risco metacrônico ou adjuvância","Incorreta. Pode ser opção individual, mas ignora aspectos essenciais do caso."],["B","Quimiorradioterapia neoadjuvante obrigatória","Incorreta. Não é padrão para cólon direito ressecável."],["C","Colectomia subtotal com anastomose ileorretal em paciente adequado, seguida de quimioterapia adjuvante","Correta entre as opções. Aborda risco metacrônico e estágio III."],["D","Radioterapia e colectomia total em todos os casos","Incorreta. Radioterapia não é rotineira."],["E","Nenhum tratamento cirúrgico","Incorreta. Há doença potencialmente curável."]]},
  {"k":"comp-paf-risco","topic":"Câncer colorretal","d":"fácil","type":"single","s":"Entre os pacientes abaixo, quem apresenta o maior risco vitalício de câncer colorretal sem tratamento preventivo?","c":["E"],"g":"PAF clássica confere risco próximo de 100% sem colectomia profilática, superior ao risco de história familiar isolada, colite ou adenoma esporádico.","sum":"PAF não tratada quase sempre evolui para câncer.","mem":"Milhares de pólipos, risco quase total.","trap":"RCU longa é alto risco, mas não alcança a penetrância da PAF clássica.","alts":[["A","Homem de 40 anos com irmão afetado","Incorreta. Risco aumenta, mas é menor."],["B","Mulher com mutação BRCA1 isolada","Incorreta. Não é a síndrome colorretal de maior penetrância."],["C","Homem com RCU há 15 anos","Incorreta. Tem risco aumentado, porém menor."],["D","Homem após ressecção de adenoma esporádico","Incorreta. Exige vigilância, mas não confere risco quase universal."],["E","Homem jovem com polipose adenomatosa familiar","Correta. O risco sem tratamento é próximo de 100%."]]},
  {"k":"comp-proctossigmoidite-terapia","topic":"Retocolite ulcerativa","d":"médio","type":"single","s":"Homem com quatro evacuações sanguinolentas ao dia e proctossigmoidite ulcerativa leve a moderada, sem toxicidade sistêmica, deve receber inicialmente:","c":["B"],"g":"Mesalazina retal é muito eficaz na doença distal e pode ser combinada à formulação oral; corticoide é reservado a resposta insuficiente.","sum":"RCU distal prefere 5-ASA retal, frequentemente com oral.","mem":"Doença baixa, remédio por baixo.","trap":"Dietas restritivas não substituem indução farmacológica.","alts":[["A","Colectomia imediata","Incorreta. Não há indicação."],["B","Mesalazina retal, associada ou não à mesalazina oral conforme extensão e resposta","Correta. É primeira linha."],["C","Nutrição parenteral e jejum","Incorreta. Não induz remissão."],["D","Antibiótico de amplo espectro","Incorreta. Não é rotina."],["E","Opioide antidiarreico","Incorreta. Pode ser perigoso na colite ativa."]]},
  {"k":"comp-colelitiase-us","topic":"Doenças biliares","d":"fácil","type":"single","s":"Em relação à colelitíase, assinale a alternativa correta.","c":["E"],"g":"Ultrassonografia é exame inicial de escolha por boa acurácia para cálculos vesiculares, disponibilidade e ausência de radiação.","sum":"Pedra na vesícula começa no ultrassom.","mem":"US vê cálculo e sombra.","trap":"Cálculos pequenos migram mais facilmente e aumentam risco de pancreatite.","alts":[["A","Complicações ocorrem exclusivamente em mulheres","Incorreta. Não são exclusivas."],["B","Perda rápida de peso protege contra cálculos","Incorreta. Aumenta o risco."],["C","Todo assintomático deve operar","Incorreta. Conduta expectante é comum."],["D","Cálculos grandes migram mais que pequenos","Incorreta. Pequenos migram com maior facilidade."],["E","Ultrassonografia é o exame inicial de escolha","Correta. É prática e segura."]]},
  {"k":"comp-necrose-nutricao","topic":"Pancreatite aguda","d":"difícil","type":"single","s":"No terceiro dia de pancreatite necrosante, sem evidência de infecção da necrose, qual estratégia adicional é mais adequada?","c":["B"],"g":"Nutrição enteral precoce é preferida à parenteral e antibiótico profilático não é recomendado na necrose estéril; intervenção é reservada a complicações.","sum":"Necrose estéril: alimente pelo intestino e não dê antibiótico profilático.","mem":"Enteral primeiro; step-up se infectar.","trap":"Febre e leucocitose podem decorrer da inflamação estéril.","alts":[["A","Nutrição parenteral, antibiótico e necrosectomia imediata","Incorreta. Intervenção precoce aumenta dano."],["B","Nutrição enteral por via oral ou sonda conforme tolerância, sem antibiótico profilático","Correta. É o suporte recomendado."],["C","CPRE de rotina sem colangite ou obstrução","Incorreta. Não há indicação."],["D","Necrosectomia aberta no terceiro dia","Incorreta. Deve ser adiada quando possível."],["E","Jejum absoluto por várias semanas","Incorreta. Prejudica barreira intestinal e nutrição."]]},
  {"k":"comp-colecistite-clinica","topic":"Doenças biliares","d":"fácil","type":"single","s":"Qual conjunto é mais típico de colecistite aguda?","c":["B"],"g":"Dor persistente em QSD, sinal de Murphy, febre e leucocitose diferenciam colecistite de cólica biliar simples.","sum":"Colecistite: dor que não passa, Murphy e inflamação.","mem":"Cólica vai e volta; colecistite fica.","trap":"Icterícia importante sugere coledocolitíase ou colangite associada.","alts":[["A","Dor intermitente, icterícia e ausência de inflamação","Incorreta. Não é o padrão típico."],["B","Dor persistente em QSD, sensibilidade/Murphy e leucocitose","Correta. É a tríade clínica mais compatível."],["C","Sensibilidade mínima e sem febre","Incorreta. Favorece cólica biliar."],["D","Dor lombar isolada","Incorreta. Não é típica."],["E","Vesícula palpável indolor e icterícia","Incorreta. É sinal de Courvoisier."]]},
  {"k":"comp-anal-linfonodo","topic":"Doenças anorretais","d":"médio","type":"true_false","s":"Sobre tumores da margem e do canal anal, julgue as assertivas.","c":["A:V","B:V","C:F","D:F"],"g":"Drenagem linfática depende da linha pectínea; tratamento moderno preserva esfíncter na maioria dos carcinomas escamosos do canal anal.","sum":"Abaixo drena para inguinal; canal anal trata com quimiorradioterapia.","mem":"Anal baixo vai para virilha.","trap":"Colostomia definitiva é reservada a falha, complicação ou doença selecionada.","alts":[["A","Lesões abaixo da linha pectínea podem metastatizar para linfonodos inguinais.","Verdadeira. A drenagem inferior segue para cadeias inguinais superficiais."],["B","Carcinoma escamoso do canal anal é geralmente tratado inicialmente com quimiorradioterapia.","Verdadeira. A estratégia preserva o esfíncter."],["C","Colostomia definitiva é necessária na maioria dos casos ao diagnóstico.","Falsa. A maioria pode evitar colostomia definitiva."],["D","Todo tumor superficial da margem anal exige amputação abdominoperineal.","Falsa. Excisão local pode ser apropriada em lesões selecionadas."]]},
  {"k":"comp-diarreia-aguda-investigacao","topic":"Diarreia aguda","d":"médio","type":"single","s":"Mulher com náuseas, febre e diarreia há três dias procura atendimento. Qual roteiro inicial é mais apropriado?","c":["C"],"g":"Avaliam-se hidratação, gravidade, sangue, duração, exposições, viagens, medicamentos e gestação; exames fecais são reservados a febre alta, disenteria, sepse, imunossupressão ou curso prolongado.","sum":"Primeiro hidrate e procure sinais de invasão.","mem":"Diarreia curta sem alarme é clínica; com sangue/febre forte, investigue fezes.","trap":"Antibiótico empírico não é rotina para toda diarreia aguda.","alts":[["A","Colonoscopia imediata para todos","Incorreta. Não é exame inicial."],["B","Antibiótico e antidiarreico sem avaliação","Incorreta. Pode ser inadequado ou perigoso."],["C","Anamnese dirigida, avaliação de hidratação e alarme, teste de gravidez quando pertinente e estudos fecais se quadro invasivo/grave","Correta. É uma abordagem racional."],["D","Jejum completo até cessar a diarreia","Incorreta. Alimentação deve ser retomada conforme tolerância."],["E","TC abdominal de rotina","Incorreta. Não é indicada sem suspeita de complicação."]]},
  {"k":"comp-celiaca-imunologia","topic":"Doença celíaca","d":"médio","type":"true_false","s":"Sobre a imunopatogênese da doença celíaca, julgue as assertivas.","c":["A:V","B:V","C:V","D:F"],"g":"Peptídeos de glúten deamidados pela transglutaminase são apresentados por HLA-DQ2/DQ8 a linfócitos T, com autoanticorpos e lesão vilositária.","sum":"Glúten + HLA + linfócito T + transglutaminase.","mem":"DQ2/8 apresenta glúten ao T.","trap":"Predisposição genética é necessária na maioria, mas não suficiente sozinha.","alts":[["A","É doença imunomediada desencadeada pelo glúten em predispostos.","Verdadeira. O gatilho ambiental atua sobre susceptibilidade genética."],["B","Linfócitos T participam da lesão mucosa.","Verdadeira. Resposta adaptativa é central."],["C","Podem ser produzidos anticorpos anti-transglutaminase e antiendomísio.","Verdadeira. São marcadores sorológicos importantes."],["D","É causada por invasão bacteriana direta das vilosidades.","Falsa. Não é uma infecção bacteriana."]]},
  {"k":"comp-crc-diagnostico","topic":"Câncer colorretal","d":"fácil","type":"single","s":"Qual exame confirma o diagnóstico de câncer colorretal e permite avaliar o restante do cólon?","c":["D"],"g":"Colonoscopia visualiza a lesão, permite biópsia e pesquisa tumores/pólipos sincrônicos.","sum":"Câncer colorretal confirma com colonoscopia e biópsia.","mem":"Veja, biopsie e percorra o cólon.","trap":"TC estagia, mas não substitui histologia.","alts":[["A","Hemograma","Incorreta. Detecta anemia."],["B","CEA isolado","Incorreta. Não confirma diagnóstico."],["C","Ultrassonografia abdominal","Incorreta. Não avalia adequadamente a mucosa colônica."],["D","Colonoscopia com biópsia","Correta. Fornece confirmação histológica."],["E","Radiografia simples","Incorreta. Não diagnostica a lesão."]]},
  {"k":"comp-distensao-radiografia","topic":"Abdome agudo","d":"fácil","type":"single","s":"Paciente apresenta distensão abdominal, vômitos e parada de eliminação de gases, com suspeita inicial de obstrução intestinal. Qual exame simples pode ser solicitado prontamente para procurar alças dilatadas e níveis hidroaéreos?","c":["B"],"g":"Radiografia de abdome pode reconhecer padrão obstrutivo inicial; TC define causa, ponto de transição e complicações.","sum":"Raio-X reconhece obstrução; TC explica.","mem":"Nível hidroaéreo aparece no abdome em pé.","trap":"Ultrassom é útil em contextos específicos, mas gás limita o exame.","alts":[["A","Endoscopia alta","Incorreta. Não é exame inicial para obstrução difusa."],["B","Radiografia de abdome","Correta. Pode mostrar distensão e níveis."],["C","Mamografia","Incorreta. Não tem relação."],["D","Ecocardiograma","Incorreta. Não avalia alças."],["E","Densitometria óssea","Incorreta. Não tem relação."]]}
 ]$data$::jsonb) AS x(k text,topic text,d text,type text,s text,c jsonb,g text,sum text,mem text,trap text,alts jsonb)
 LOOP
  SELECT id INTO v_topic_id FROM public.topics WHERE discipline_id=v_discipline_id AND name=q.topic LIMIT 1;
  IF v_topic_id IS NULL THEN v_topic_id:=pg_temp.gastro_comp_uuid('gastro-topic-'||q.topic); INSERT INTO public.topics(id,discipline_id,name) VALUES(v_topic_id,v_discipline_id,q.topic) ON CONFLICT(id) DO UPDATE SET name=EXCLUDED.name; END IF;
  v_question_id:=pg_temp.gastro_comp_uuid('gastro-p3-'||q.k);
  INSERT INTO public.questions(id,discipline_id,topic_id,exam,difficulty,statement,question_type,correct_answer,correct_answers,general_comment,summary,memory_tip,trap,reference,active,image_url) VALUES(v_question_id,v_discipline_id,v_topic_id,'P3',q.d,q.s,q.type,split_part(q.c->>0, ':', 1),ARRAY(SELECT jsonb_array_elements_text(q.c)),q.g,q.sum,q.mem,q.trap,'Prova 3 de Gastroenterologia — payload deduplicado e revisado em 2026.',true,NULL) ON CONFLICT(id) DO UPDATE SET topic_id=EXCLUDED.topic_id,exam='P3',difficulty=EXCLUDED.difficulty,statement=EXCLUDED.statement,question_type=EXCLUDED.question_type,correct_answer=EXCLUDED.correct_answer,correct_answers=EXCLUDED.correct_answers,general_comment=EXCLUDED.general_comment,summary=EXCLUDED.summary,memory_tip=EXCLUDED.memory_tip,trap=EXCLUDED.trap,reference=EXCLUDED.reference,active=true,image_url=NULL;
  DELETE FROM public.alternatives WHERE question_id=v_question_id;
  FOR a IN SELECT value FROM jsonb_array_elements(q.alts) LOOP INSERT INTO public.alternatives(id,question_id,letter,text,explanation) VALUES(pg_temp.gastro_comp_uuid(v_question_id::text||(a->>0)),v_question_id,a->>0,a->>1,a->>2); END LOOP;
 END LOOP;
END $$;
DO $$ DECLARE v_count integer; v_blank integer; BEGIN
 SELECT count(*) INTO v_count FROM public.questions WHERE id IN (SELECT pg_temp.gastro_comp_uuid('gastro-p3-'||key) FROM unnest(ARRAY['comp-disabsorcao-exame-menos-util','comp-lynch-cirurgia','comp-paf-risco','comp-proctossigmoidite-terapia','comp-colelitiase-us','comp-necrose-nutricao','comp-colecistite-clinica','comp-anal-linfonodo','comp-diarreia-aguda-investigacao','comp-celiaca-imunologia','comp-crc-diagnostico','comp-distensao-radiografia']) AS keys(key));
 SELECT count(*) INTO v_blank FROM public.alternatives a JOIN public.questions q ON q.id=a.question_id WHERE q.id IN (SELECT pg_temp.gastro_comp_uuid('gastro-p3-'||key) FROM unnest(ARRAY['comp-disabsorcao-exame-menos-util','comp-lynch-cirurgia','comp-paf-risco','comp-proctossigmoidite-terapia','comp-colelitiase-us','comp-necrose-nutricao','comp-colecistite-clinica','comp-anal-linfonodo','comp-diarreia-aguda-investigacao','comp-celiaca-imunologia','comp-crc-diagnostico','comp-distensao-radiografia']) AS keys(key)) AND (coalesce(trim(a.text),'')='' OR coalesce(trim(a.explanation),'')='');
 IF v_count<>12 OR v_blank<>0 THEN RAISE EXCEPTION 'Auditoria complementos falhou: questões=%, vazias=%',v_count,v_blank; END IF;
END $$;
COMMIT;
