-- Segundo lote da monitoria: abdome agudo, diarreias, câncer colorretal,
-- doença diverticular e questões de 2016. Itens ambíguos foram corrigidos.
BEGIN;

CREATE OR REPLACE FUNCTION pg_temp.gastro_mon2_uuid(seed text) RETURNS uuid
LANGUAGE sql IMMUTABLE AS $$
  SELECT (substr(md5(seed),1,8)||'-'||substr(md5(seed),9,4)||'-5'||substr(md5(seed),14,3)||'-a'||substr(md5(seed),18,3)||'-'||substr(md5(seed),21,12))::uuid
$$;

DO $$
DECLARE
  v_discipline_id uuid; v_topic_id uuid; v_question_id uuid; q record; a jsonb;
BEGIN
  SELECT id INTO v_discipline_id FROM public.disciplines WHERE slug='gastroenterologia' LIMIT 1;
  IF v_discipline_id IS NULL THEN RAISE EXCEPTION 'Disciplina Gastroenterologia não encontrada'; END IF;

  FOR q IN SELECT * FROM jsonb_to_recordset($data$[
    {"k":"mon-perfurativo-jobert","topic":"Abdome agudo","d":"médio","type":"single","s":"Homem de 32 anos, usuário frequente de anti-inflamatórios, apresenta dor abdominal súbita intensa, defesa difusa e sinal de Jobert positivo. Qual o diagnóstico sindrômico mais provável?","c":["D"],"g":"Jobert corresponde à perda da macicez hepática por ar livre intraperitoneal e, com peritonite, sugere perfuração de víscera oca.","sum":"Pneumoperitônio + peritonite = abdome agudo perfurativo.","mem":"Jobert: ar no lugar do fígado.","trap":"Pancreatite pode causar dor intensa, mas não costuma gerar pneumoperitônio.","alts":[["A","Apendicite não complicada","Incorreta. O quadro é difuso e há sinal de pneumoperitônio."],["B","Pancreatite aguda","Incorreta. Não explica sinal de Jobert."],["C","Isquemia mesentérica sem perfuração","Incorreta. Pode evoluir com peritonite, mas Jobert aponta ar livre."],["D","Abdome agudo perfurativo, possivelmente por úlcera péptica","Correta. AINEs aumentam risco de úlcera e perfuração."],["E","Colecistite aguda","Incorreta. Produz dor em QSD sem pneumoperitônio típico."]]},
    {"k":"mon-isquemia-mesenterica-clinica","topic":"Abdome agudo","d":"médio","type":"single","s":"Homem de 70 anos, cardiopata, apresenta dor abdominal abrupta e muito intensa, desproporcional ao exame inicial, com abdome ainda flácido. Qual diagnóstico deve ser priorizado?","c":["C"],"g":"Dor desproporcional aos achados em paciente com risco cardiovascular é apresentação clássica de isquemia mesentérica aguda.","sum":"Muita dor e pouco exame no início: isquemia mesentérica.","mem":"Dor fora de proporção pede angio-TC.","trap":"Peritonismo pode surgir tardiamente, após necrose intestinal.","alts":[["A","Úlcera perfurada","Incorreta. Costuma produzir irritação peritoneal precoce."],["B","Pancreatite aguda","Incorreta. A dor pode ser intensa, mas o contexto vascular é mais sugestivo."],["C","Isquemia mesentérica aguda","Correta. É emergência vascular tempo-dependente."],["D","Pielonefrite","Incorreta. Faltam sintomas urinários e dor lombar."],["E","Apendicite inicial","Incorreta. Idade, intensidade e início abrupto não são típicos."]]},
    {"k":"mon-crc-risco-exceto","topic":"Câncer colorretal","d":"médio","type":"single","s":"São fatores reconhecidos de risco aumentado para câncer colorretal, exceto:","c":["B"],"g":"Idade aumenta risco de forma contínua, mas o corte antigo de 40 anos isoladamente não constitui fator clínico de alto risco; rastreio de risco médio inicia-se conforme diretriz populacional.","sum":"Família, PAF, adenomas avançados e colite longa são alto risco.","mem":"Quarenta isolado não é síndrome de alto risco.","trap":"Idade é fator populacional, mas não equivale aos grupos hereditários ou inflamatórios.","alts":[["A","Parente de primeiro grau com câncer colorretal","Incorreta como resposta. Aumenta risco."],["B","Ter apenas 40 anos, sem história pessoal ou familiar adicional","Correta como exceção. Não define, isoladamente, grupo clínico de alto risco."],["C","Retocolite ulcerativa extensa e duradoura","Incorreta como resposta. Aumenta risco."],["D","Polipose adenomatosa familiar","Incorreta como resposta. Confere risco extremo."],["E","Adenomas múltiplos ou avançados prévios","Incorreta como resposta. Exigem vigilância específica."]]},
    {"k":"mon-pancreas-correlacao","topic":"Pancreatites","d":"médio","type":"true_false","s":"Relacione cada apresentação pancreática ao diagnóstico mais provável, julgando se a correlação proposta está correta.","c":["A:V","B:V","C:V","D:V"],"g":"Etiologia e estágio são inferidos pelo contexto: biliar em mulher com perfil clássico, hipertrigliceridemia em diabético obeso, calcificações na crônica e esteatorreia na insuficiência exócrina.","sum":"Aguda biliar; aguda metabólica; crônica calcifica; insuficiência causa esteatorreia.","mem":"Pedra, triglicéride, cálcio e gordura nas fezes.","trap":"Nenhuma associação isolada substitui investigação etiológica.","alts":[["A","Mulher com dor epigástrica aguda irradiada para dorso, febre e vômitos: pancreatite aguda biliar é hipótese plausível.","Verdadeira. Sexo feminino e apresentação aguda são compatíveis, devendo-se investigar litíase."],["B","Homem obeso e diabético com pancreatite aguda: hipertrigliceridemia deve ser considerada.","Verdadeira. Diabetes descompensado pode acompanhar triglicerídeos muito elevados."],["C","Calcificações na topografia pancreática em paciente com dor crônica sugerem pancreatite crônica.","Verdadeira. Calcificações são achado de doença avançada."],["D","Dor crônica, perda ponderal, diabetes e esteatorreia sugerem insuficiência pancreática associada à pancreatite crônica.","Verdadeira. Há comprometimento exócrino e endócrino."]]},
    {"k":"mon-lactose-diagnostico","topic":"Diarreia crônica","d":"médio","type":"single","s":"Adulto com distensão, flatulência e diarreia após laticínios melhora ao retirar lactose. Qual teste não invasivo é mais apropriado para confirmar má absorção de lactose quando necessário?","c":["B"],"g":"Teste respiratório de hidrogênio após carga de lactose é o método não invasivo mais utilizado; resposta a teste dietético também pode apoiar o diagnóstico.","sum":"Lactose não absorvida fermenta e libera hidrogênio expirado.","mem":"Lactose vira H₂ no sopro.","trap":"Biópsia de intestino delgado não é exame inicial para intolerância isolada.","alts":[["A","Coprocultura seriada","Incorreta. Avalia infecção bacteriana."],["B","Teste respiratório de hidrogênio com lactose","Correta. Detecta fermentação de lactose não absorvida."],["C","Colonoscopia com biópsias","Incorreta. Não mede atividade de lactase."],["D","CA 19-9 sérico","Incorreta. É marcador oncológico sem papel aqui."],["E","Teste de tolerância à glicose","Incorreta. Não avalia absorção de lactose."]]},
    {"k":"mon-dxilose-finalidade","topic":"Síndromes disabsortivas","d":"médio","type":"single","s":"Historicamente, o teste de D-xilose foi utilizado principalmente para qual finalidade na investigação de má absorção?","c":["C"],"g":"D-xilose é absorvida pela mucosa proximal sem depender de enzimas pancreáticas; resultado baixo sugere doença mucosa, enquanto resultado preservado com esteatorreia favorece insuficiência pancreática.","sum":"D-xilose separa mucosa do pâncreas.","mem":"Xilose pula o pâncreas.","trap":"O teste tem uso atual limitado e foi substituído por exames mais específicos em muitos centros.","alts":[["A","Confirmar intolerância à glicose","Incorreta. Não é teste de metabolismo glicêmico."],["B","Diagnosticar retocolite ulcerativa","Incorreta. RCU é avaliada por endoscopia e histologia."],["C","Diferenciar doença da mucosa do intestino delgado de insuficiência pancreática","Correta. A absorção independe da digestão pancreática."],["D","Estadiar câncer colorretal","Incorreta. Não tem papel oncológico."],["E","Diagnosticar diabetes mellitus","Incorreta. Não substitui glicemia ou HbA1c."]]},
    {"k":"mon-diarreia-cronica-afirmativas","topic":"Diarreia crônica","d":"médio","type":"single","s":"Na investigação da diarreia crônica, avalie: I. Esteatorreia é definida classicamente por gordura fecal acima de 7 g/24 h sob dieta padronizada. II. Supercrescimento bacteriano pode coexistir com sintomas semelhantes à SII. III. Mucosa duodenal macroscopicamente normal exclui doença celíaca. Quais estão corretas?","c":["D"],"g":"I e II são verdadeiras; alterações celíacas podem ser microscópicas, exigindo biópsias adequadas mesmo com aparência endoscópica normal.","sum":"Gordura >7; SIBO pode mimetizar; duodeno normal à vista não exclui celíaca.","mem":"Celíaca pode se esconder no microscópio.","trap":"Não confunda aparência normal com histologia normal.","alts":[["A","I apenas","Incorreta. II também é verdadeira."],["B","II apenas","Incorreta. I também é verdadeira."],["C","III apenas","Incorreta. III é falsa."],["D","I e II apenas","Correta. É a combinação adequada."],["E","I, II e III","Incorreta. III é falsa."]]},
    {"k":"mon-whipple-tratamento-atual","topic":"Síndromes disabsortivas","d":"difícil","type":"single","s":"Após confirmação de doença de Whipple sem contraindicações, qual princípio terapêutico é mais apropriado?","c":["E"],"g":"O tratamento deve usar antibióticos com penetração no sistema nervoso central e manutenção prolongada; esquemas variam e acompanhamento especializado é essencial pelo risco de recaída.","sum":"Whipple exige indução sistêmica e manutenção longa com cobertura de SNC.","mem":"Whipple trata por muito tempo e pensando no cérebro.","trap":"Sulfametoxazol-trimetoprima era resposta tradicional, mas há resistência e esquemas atuais frequentemente preferem ceftriaxona/meropenem seguidos de doxiciclina com hidroxicloroquina.","alts":[["A","Ciprofloxacino isolado por três dias","Incorreta. Duração e esquema são inadequados."],["B","Azitromicina em dose única","Incorreta. Não erradica infecção sistêmica."],["C","Clindamicina tópica","Incorreta. Não tem papel."],["D","Amoxicilina-clavulanato por sete dias","Incorreta. Tratamento curto favorece recaída."],["E","Indução com agente de boa penetração no SNC, como ceftriaxona, seguida de manutenção prolongada definida por especialista","Correta. Reflete o princípio terapêutico contemporâneo."]]},
    {"k":"mon-megacolon-toxico","topic":"Retocolite ulcerativa","d":"médio","type":"single","s":"Paciente com colite sanguinolenta grave apresenta febre, taquicardia, anemia, leucocitose e dilatação importante do cólon transverso. Qual a principal complicação?","c":["C"],"g":"Dilatação colônica não obstrutiva associada a toxicidade sistêmica define megacólon tóxico, emergência com risco de perfuração.","sum":"Cólon dilatado + toxicidade = megacólon tóxico.","mem":"Mega no raio-X, tóxico nos sinais vitais.","trap":"Evite antidiarreicos, opioides e colonoscopia completa na fase aguda.","alts":[["A","Crohn ileal não complicado","Incorreta. Não explica dilatação colônica tóxica."],["B","Síndrome do intestino irritável","Incorreta. Não causa inflamação ou dilatação grave."],["C","Megacólon tóxico","Correta. O caso reúne critérios radiológicos e sistêmicos."],["D","Proctite leve","Incorreta. O quadro é sistêmico e extenso."],["E","Constipação funcional","Incorreta. Há colite inflamatória grave."]]},
    {"k":"mon-sii-c-tratamento","topic":"Síndrome do intestino irritável","d":"médio","type":"single","s":"Em paciente com SII com predomínio de constipação, qual combinação entre as opções antigas é mais coerente para alívio de cólica e melhora do trânsito?","c":["C"],"g":"Fibra solúvel como psyllium pode ajudar SII-C; antiespasmódico pode aliviar dor, enquanto loperamida pioraria constipação.","sum":"SII-C: fibra solúvel e terapia voltada à constipação; evite loperamida.","mem":"C de constipação não combina com loperamida.","trap":"Hoje também há PEG e secretagogos, individualizados conforme disponibilidade e resposta.","alts":[["A","Brometo de otilônio e loperamida","Incorreta. Loperamida reduz trânsito."],["B","Brometo de pinavério e loperamida","Incorreta. Mantém o mesmo problema."],["C","Antiespasmódico e psyllium","Correta entre as opções. Atua em dor e consistência/frequência."],["D","Antiespasmódico e metronidazol","Incorreta. Antibiótico não é tratamento rotineiro de SII-C."],["E","Loperamida isolada","Incorreta. Pode agravar constipação."]]},
    {"k":"mon-apendicite-adulta","topic":"Abdome agudo","d":"fácil","type":"single","s":"Mulher de 50 anos apresenta dor iniciada em região periumbilical que migrou para fossa ilíaca direita, febre, anorexia, náuseas e descompressão dolorosa. Qual hipótese é mais provável?","c":["B"],"g":"Migração da dor para FID com febre, anorexia e peritonismo é apresentação clássica de apendicite aguda.","sum":"Dor migratória para FID = apendicite.","mem":"Visceral no umbigo, somática na FID.","trap":"Em mulheres, causas ginecológicas entram no diferencial, mas não superam este padrão clássico.","alts":[["A","Pancreatite aguda","Incorreta. Dor seria tipicamente epigástrica."],["B","Apendicite aguda","Correta. Explica evolução e sinais locais."],["C","Gastroenterite","Incorreta. Não costuma causar peritonismo focal progressivo."],["D","Salpingite","Incorreta. É diferencial, mas faltam sintomas pélvicos e o padrão migratório favorece apendicite."],["E","Pielonefrite","Incorreta. Faltam sintomas urinários e dor lombar."]]},
    {"k":"mon-crc-fator-protetor","topic":"Câncer colorretal","d":"médio","type":"single","s":"Qual exposição está associada à redução do risco de adenomas e câncer colorretal, embora não deva ser iniciada indiscriminadamente apenas para esse fim?","c":["C"],"g":"Aspirina e alguns AINEs reduzem incidência de adenomas/CRC, mas risco de sangramento impede recomendação universal; decisão preventiva é individualizada.","sum":"Aspirina pode proteger o cólon, mas pode sangrar.","mem":"Benefício oncológico não apaga risco hemorrágico.","trap":"Não prescreva prevenção sem avaliar risco cardiovascular e hemorrágico.","alts":[["A","Sedentarismo","Incorreta. Associa-se a maior risco."],["B","Consumo excessivo de álcool","Incorreta. Aumenta risco."],["C","Uso de aspirina/AINE em contextos selecionados","Correta. Há efeito quimiopreventivo documentado, com ressalvas."],["D","Tabagismo","Incorreta. Aumenta risco de neoplasias."],["E","Alto consumo de carne processada","Incorreta. Associa-se a maior risco."]]},
    {"k":"mon-diverticulite-hinchey","topic":"Doença diverticular","d":"médio","type":"single","s":"Sobre doença diverticular e diverticulite aguda, assinale a alternativa correta.","c":["E"],"g":"Peritonite purulenta ou fecal generalizada, correspondente a Hinchey III/IV, geralmente exige abordagem cirúrgica urgente e controle de foco.","sum":"Hinchey III/IV = peritonite e cirurgia.","mem":"Três e quatro, opere sem demora.","trap":"Fístula crônica costuma indicar cirurgia eletiva, não necessariamente emergência.","alts":[["A","Fístula colovesical exige sempre cirurgia na mesma hora","Incorreta. Geralmente é indicação eletiva após controle da infecção."],["B","Toda hemorragia diverticular exige cirurgia urgente","Incorreta. Muitas cessam espontaneamente e manejo é escalonado."],["C","Colonoscopia é exame inicial de escolha durante diverticulite aguda","Incorreta. TC é preferida; colonoscopia é adiada."],["D","Antibiótico deve cobrir apenas gram-positivos","Incorreta. Quando indicado, cobre gram-negativos e anaeróbios."],["E","Hinchey III e IV são indicações de controle cirúrgico urgente do foco","Correta. Há peritonite generalizada."]]},
    {"k":"mon-malabsorcao-exceto","topic":"Síndromes disabsortivas","d":"fácil","type":"single","s":"São manifestações possíveis de síndrome de má absorção intestinal, exceto:","c":["C"],"g":"Má absorção causa distensão, perda ponderal, esteatorreia e fezes volumosas; tenesmo indica processo retal/colônico distal.","sum":"Tenesmo vem do reto, não da absorção do delgado.","mem":"Má absorção engorda as fezes; proctite dá tenesmo.","trap":"Restos alimentares isolados são inespecíficos.","alts":[["A","Distensão abdominal","Incorreta como resposta. É comum."],["B","Fezes volumosas com restos alimentares","Incorreta como resposta. Pode ocorrer em trânsito acelerado/má digestão."],["C","Tenesmo retal","Correta como exceção. Sugere doença distal."],["D","Perda ponderal","Incorreta como resposta. É manifestação de déficit nutricional."],["E","Fezes gordurosas ou espumosas","Incorreta como resposta. Podem refletir esteatorreia."]]},
    {"k":"mon-celiaca-incorreta","topic":"Doença celíaca","d":"fácil","type":"single","s":"Com relação à doença celíaca, assinale a alternativa incorreta.","c":["B"],"g":"Doença celíaca pode ser diagnosticada em qualquer idade e associa autoimunidade ao glúten em indivíduos geneticamente predispostos.","sum":"Celíaca não é só da infância.","mem":"Glúten não respeita idade.","trap":"Adultos podem ter anemia, osteopenia ou sintomas mínimos em vez de diarreia clássica.","alts":[["A","Anti-transglutaminase IgA integra a investigação","Incorreta como resposta. É verdadeiro, junto à IgA total."],["B","É doença exclusiva da infância","Correta como incorreta. Pode surgir em adultos e idosos."],["C","Pode associar-se à dermatite herpetiforme","Incorreta como resposta. É verdadeiro."],["D","O tratamento é dieta isenta de glúten","Incorreta como resposta. É verdadeiro e permanente."],["E","Pode causar síndrome de má absorção","Incorreta como resposta. É verdadeiro."]]},
    {"k":"mon-crohn-exceto","topic":"Doença de Crohn","d":"médio","type":"single","s":"São características da doença de Crohn, exceto:","c":["A"],"g":"Crohn pode acometer da boca ao ânus, frequentemente íleo terminal, e causar doença perianal; acometimento retal universal é típico de RCU, não Crohn.","sum":"Crohn salta e pode poupar reto.","mem":"Crohn escolhe trechos; RCU começa no reto.","trap":"Crohn colônico pode atingir o reto, mas não na grande maioria obrigatoriamente.","alts":[["A","Acometimento retal na grande maioria dos pacientes","Correta como exceção. O reto pode ser poupado."],["B","Possibilidade de acometer qualquer segmento da boca à região perianal","Incorreta como resposta. É verdadeiro."],["C","Comprometimento isolado do íleo terminal","Incorreta como resposta. É apresentação frequente."],["D","Doença ileocolônica e manifestações perianais","Incorreta como resposta. São padrões reconhecidos."],["E","Inflamação transmural com fístulas","Incorreta como resposta. É característica central."]]},
    {"k":"mon-apendicite-diferencial","topic":"Abdome agudo","d":"médio","type":"single","s":"Em mulher jovem com quadro clássico de apendicite, todas as condições abaixo entram no diagnóstico diferencial de dor em fossa ilíaca direita, exceto:","c":["A"],"g":"Adenite mesentérica, gestação ectópica, cólica ureteral e torção de omento podem mimetizar apendicite; úlcera perfurada costuma causar dor epigástrica e pneumoperitônio.","sum":"FID tem diferenciais intestinais, ginecológicos e urinários.","mem":"Úlcera começa em cima; apêndice dói embaixo à direita.","trap":"Conteúdo perfurado pode escorrer para FID, mas não é o diferencial típico pretendido.","alts":[["A","Úlcera péptica perfurada","Correta como exceção entre os diferenciais típicos listados."],["B","Adenite mesentérica","Incorreta como resposta. É mimetizador clássico."],["C","Gestação ectópica rota","Incorreta como resposta. Deve ser excluída em idade fértil."],["D","Cólica ureteral direita","Incorreta como resposta. Pode causar dor semelhante."],["E","Torção de omento","Incorreta como resposta. Pode simular apendicite."]]},
    {"k":"mon-goodsall","topic":"Doenças anorretais","d":"médio","type":"single","s":"Segundo a regra de Goodsall, qual trajeto é mais provável para uma fístula anal com orifício externo anterior e próximo ao ânus?","c":["B"],"g":"Orifícios anteriores a até cerca de 3 cm da margem tendem a seguir trajeto radial curto e retilíneo; posteriores tendem a curvar até a linha média posterior.","sum":"Anterior perto: reto e radial; posterior: curva para trás.","mem":"Anterior aponta; posterior contorna.","trap":"Orifícios anteriores distantes podem ser exceção e seguir trajeto curvo.","alts":[["A","Trajeto longo e curvo até linha média posterior em todos os casos","Incorreta. É padrão posterior e há exceções por distância."],["B","Trajeto curto, radial e relativamente retilíneo","Correta. É a previsão clássica."],["C","Ausência obrigatória de supuração","Incorreta. Fístulas podem drenar."],["D","Associação obrigatória com Crohn","Incorreta. A maioria é criptoglandular."],["E","Prognóstico necessariamente desfavorável","Incorreta. Depende da anatomia e continência."]]},
    {"k":"mon-diarreia-nao-invasiva","topic":"Diarreia aguda","d":"médio","type":"multiple","s":"Quais agentes abaixo tipicamente causam diarreia aquosa não inflamatória, sem sangue nas fezes? Selecione todas as corretas.","c":["D","E"],"g":"Rotavírus e E. coli enterotoxigênica causam diarreia aquosa; Shigella, E. histolytica e Salmonella invasiva podem causar disenteria.","sum":"Vírus e enterotoxina dão água; invasores dão sangue.","mem":"ETEC toxina, rota água.","trap":"A questão antiga aceitava uma resposta, mas possuía duas alternativas corretas.","alts":[["A","Shigella","Incorreta. É causa clássica de disenteria."],["B","Entamoeba histolytica","Incorreta. Pode causar colite amebiana sanguinolenta."],["C","Salmonella não tifoide invasiva","Incorreta. Pode causar inflamação e sangue."],["D","Rotavírus","Correta. Produz gastroenterite aquosa."],["E","Escherichia coli enterotoxigênica","Correta. Enterotoxinas produzem secreção aquosa sem invasão."]]}
  ]$data$::jsonb) AS x(k text,topic text,d text,type text,s text,c jsonb,g text,sum text,mem text,trap text,alts jsonb)
  LOOP
    SELECT id INTO v_topic_id FROM public.topics WHERE discipline_id=v_discipline_id AND name=q.topic LIMIT 1;
    IF v_topic_id IS NULL THEN
      v_topic_id:=pg_temp.gastro_mon2_uuid('gastro-topic-'||q.topic);
      INSERT INTO public.topics(id,discipline_id,name) VALUES(v_topic_id,v_discipline_id,q.topic)
      ON CONFLICT(id) DO UPDATE SET name=EXCLUDED.name;
    END IF;
    v_question_id:=pg_temp.gastro_mon2_uuid('gastro-p3-'||q.k);
    INSERT INTO public.questions(id,discipline_id,topic_id,exam,difficulty,statement,question_type,correct_answer,correct_answers,general_comment,summary,memory_tip,trap,reference,active,image_url)
    VALUES(v_question_id,v_discipline_id,v_topic_id,'P3',q.d,q.s,q.type,q.c->>0,ARRAY(SELECT jsonb_array_elements_text(q.c)),q.g,q.sum,q.mem,q.trap,'Prova 3 de Gastroenterologia — payload deduplicado e revisado em 2026.',true,NULL)
    ON CONFLICT(id) DO UPDATE SET topic_id=EXCLUDED.topic_id,exam='P3',difficulty=EXCLUDED.difficulty,statement=EXCLUDED.statement,question_type=EXCLUDED.question_type,correct_answer=EXCLUDED.correct_answer,correct_answers=EXCLUDED.correct_answers,general_comment=EXCLUDED.general_comment,summary=EXCLUDED.summary,memory_tip=EXCLUDED.memory_tip,trap=EXCLUDED.trap,reference=EXCLUDED.reference,active=true,image_url=NULL;
    DELETE FROM public.alternatives WHERE question_id=v_question_id;
    FOR a IN SELECT value FROM jsonb_array_elements(q.alts) LOOP
      INSERT INTO public.alternatives(id,question_id,letter,text,explanation)
      VALUES(pg_temp.gastro_mon2_uuid(v_question_id::text||(a->>0)),v_question_id,a->>0,a->>1,a->>2);
    END LOOP;
  END LOOP;
END $$;

DO $$
DECLARE v_count integer; v_blank integer;
BEGIN
  SELECT count(*) INTO v_count FROM public.questions WHERE id IN (
    SELECT pg_temp.gastro_mon2_uuid('gastro-p3-'||key) FROM unnest(ARRAY[
      'mon-perfurativo-jobert','mon-isquemia-mesenterica-clinica','mon-crc-risco-exceto',
      'mon-pancreas-correlacao','mon-lactose-diagnostico','mon-dxilose-finalidade',
      'mon-diarreia-cronica-afirmativas','mon-whipple-tratamento-atual','mon-megacolon-toxico',
      'mon-sii-c-tratamento','mon-apendicite-adulta','mon-crc-fator-protetor',
      'mon-diverticulite-hinchey','mon-malabsorcao-exceto','mon-celiaca-incorreta',
      'mon-crohn-exceto','mon-apendicite-diferencial','mon-goodsall','mon-diarreia-nao-invasiva'
    ]) AS keys(key));
  SELECT count(*) INTO v_blank FROM public.alternatives a JOIN public.questions q ON q.id=a.question_id
  WHERE q.id IN (SELECT pg_temp.gastro_mon2_uuid('gastro-p3-'||key) FROM unnest(ARRAY[
      'mon-perfurativo-jobert','mon-isquemia-mesenterica-clinica','mon-crc-risco-exceto',
      'mon-pancreas-correlacao','mon-lactose-diagnostico','mon-dxilose-finalidade',
      'mon-diarreia-cronica-afirmativas','mon-whipple-tratamento-atual','mon-megacolon-toxico',
      'mon-sii-c-tratamento','mon-apendicite-adulta','mon-crc-fator-protetor',
      'mon-diverticulite-hinchey','mon-malabsorcao-exceto','mon-celiaca-incorreta',
      'mon-crohn-exceto','mon-apendicite-diferencial','mon-goodsall','mon-diarreia-nao-invasiva'
    ]) AS keys(key)) AND (coalesce(trim(a.text),'')='' OR coalesce(trim(a.explanation),'')='');
  IF v_count<>19 OR v_blank<>0 THEN RAISE EXCEPTION 'Auditoria monitoria 2 falhou: questões=%, vazias=%',v_count,v_blank; END IF;
END $$;
COMMIT;
