-- Payload deduplicado da Prova 3 de Gastroenterologia.
-- Gabaritos revistos em agosto de 2026. Blocos V/F permanecem agrupados.
BEGIN;

CREATE OR REPLACE FUNCTION pg_temp.gastro_p3_uuid(seed text) RETURNS uuid
LANGUAGE sql IMMUTABLE AS $$
  SELECT (substr(md5(seed),1,8)||'-'||substr(md5(seed),9,4)||'-5'||substr(md5(seed),14,3)||'-a'||substr(md5(seed),18,3)||'-'||substr(md5(seed),21,12))::uuid
$$;

DO $$
DECLARE
  v_discipline_id uuid;
  v_topic_id uuid;
  v_question_id uuid;
  q record;
  a jsonb;
BEGIN
  INSERT INTO public.disciplines(id,name,slug)
  VALUES(pg_temp.gastro_p3_uuid('discipline-gastroenterologia'),'Gastroenterologia','gastroenterologia')
  ON CONFLICT(slug) DO UPDATE SET name=EXCLUDED.name
  RETURNING id INTO v_discipline_id;

  FOR q IN SELECT * FROM jsonb_to_recordset($data$[
    {"k":"t108a-q2","topic":"Síndromes disabsortivas","d":"médio","type":"true_false","s":"A síndrome de má absorção pode variar de esteatorreia a apresentações discretas. Julgue cada assertiva.","c":["A:V","B:V","C:V","D:F","E:F"],"g":"Má absorção pode decorrer de falha de mistura, infecção ou deficiência enzimática; Crohn e Whipple têm mecanismos próprios.","sum":"Diferencie defeitos de mistura, digestão intraluminal e lesão da mucosa.","mem":"Bilroth II mistura; Giardia infecta; lactase causa osmose.","trap":"Não atribua achados de Crohn à doença celíaca nem Whipple ao HLA-B27.","alts":[["A","Após gastrectomia parcial com reconstrução Billroth II, a chegada dessincronizada de quimo e secreções biliopancreáticas pode causar distúrbio da mistura.","Verdadeira. A reconstrução pode separar temporalmente o quimo das secreções necessárias à digestão intraluminal."],["B","Giardia intestinalis é causa relevante de má absorção, especialmente em áreas com saneamento precário.","Verdadeira. A giardíase pode lesar a borda em escova e produzir diarreia e má absorção."],["C","A deficiência adquirida de lactase é causa comum de má absorção seletiva de carboidratos e pode provocar diarreia osmótica.","Verdadeira. Lactose não absorvida retém água e é fermentada pela microbiota."],["D","Na doença celíaca, a colonoscopia tipicamente mostra úlceras aftoides descontínuas no cólon.","Falsa. Esse padrão sugere Crohn; a avaliação histológica da doença celíaca é feita por biópsias duodenais."],["E","A doença de Whipple decorre de predisposição HLA-B27 e de um distúrbio imunológico primário.","Falsa. É uma infecção sistêmica por Tropheryma whipplei."]] },
    {"k":"t108b-q2","topic":"Doença celíaca","d":"médio","type":"true_false","s":"Sobre doença celíaca, julgue cada assertiva.","c":["A:F","B:F","C:F","D:V","E:F"],"g":"A doença celíaca pode surgir em qualquer idade, exige dieta sem glúten permanente e, em adultos, costuma ser confirmada histologicamente.","sum":"Sorologia orienta; biópsias duodenais confirmam na maioria dos adultos; dieta é vitalícia.","mem":"Celíaca não tem idade e o glúten não volta.","trap":"A adesão à dieta reduz, mas não transforma automaticamente em zero, o risco de complicações.","alts":[["A","A doença celíaca é diagnosticada apenas na infância e adolescência.","Falsa. O primodiagnóstico ocorre também em adultos e idosos."],["B","O conceito de sensibilidade ao glúten inclui automaticamente aftas recorrentes, nefropatia e artropatia como doenças específicas causadas pelo glúten.","Falsa. Essas associações não integram, isoladamente, uma definição diagnóstica uniforme de doença relacionada ao glúten."],["C","O risco de neoplasia permanece igualmente elevado mesmo em pacientes com adesão rigorosa e sustentada à dieta sem glúten.","Falsa. A adesão reduz o excesso de risco, embora a avaliação seja individualizada."],["D","Em adultos com suspeita de doença celíaca, múltiplas biópsias do bulbo e duodeno distal durante endoscopia integram a confirmação diagnóstica habitual.","Verdadeira. A distribuição pode ser irregular, por isso são necessárias amostras de mais de um segmento."],["E","Após dois anos sem sintomas, o glúten pode ser reintroduzido progressivamente.","Falsa. O tratamento é dieta isenta de glúten por toda a vida."]] },
    {"k":"hemorroidas-vf","topic":"Doenças anorretais","d":"médio","type":"true_false","s":"Em relação à doença hemorroidária, julgue cada assertiva.","c":["A:V","B:V","C:F","D:F","E:V"],"g":"A linha pectínea explica diferenças de sensibilidade e orienta tratamentos de hemorroidas internas e externas.","sum":"Internas sangram; externas trombosadas doem; Milligan–Morgan é aberta.","mem":"Morgan mantém o leito aberto.","trap":"Não confunda Milligan–Morgan com Ferguson, que fecha o leito.","alts":[["A","Hemorroidas internas são a fonte mais típica de sangramento vermelho vivo indolor.","Verdadeira. Elas se localizam acima da linha pectínea e costumam sangrar sem dor."],["B","Ligadura elástica não deve ser aplicada a hemorroidas externas.","Verdadeira. A região externa é somaticamente inervada e a ligadura causaria dor intensa."],["C","Hemorroidas internas não complicadas doem mais que as externas.","Falsa. Hemorroidas internas são geralmente indolores; trombose externa pode ser muito dolorosa."],["D","Na técnica de Milligan–Morgan, o leito é fechado por sutura após a excisão.","Falsa. Milligan–Morgan é hemorroidectomia aberta; Ferguson é a técnica fechada."],["E","Estenose anal é complicação grave possível após hemorroidectomia extensa.","Verdadeira. Excisão circunferencial excessiva pode provocar cicatrização estenosante."]] },
    {"k":"constipacao-vf","topic":"Constipação intestinal","d":"médio","type":"true_false","s":"Em relação à constipação intestinal, julgue cada assertiva.","c":["A:V","B:F","C:F","D:F"],"g":"Constipação pode ocorrer com trânsito normal; investigação e rastreio devem ser guiados por história, sinais de alarme e idade, e o tratamento é escalonado.","sum":"Comece com hábitos e fibra; laxativos osmóticos costumam preceder estimulantes.","mem":"Trânsito normal também constipa.","trap":"Não solicite colonoscopia apenas por um corte etário isolado e não confunda hipo com hipertireoidismo.","alts":[["A","A constipação pode ocorrer mesmo com trânsito colônico normal.","Verdadeira. Constipação funcional de trânsito normal é uma apresentação reconhecida."],["B","Na investigação, deve-se excluir especialmente hipertireoidismo como causa metabólica clássica.","Falsa. Hipotireoidismo, e não hipertireoidismo, é associação clássica."],["C","Toda pessoa com mais de 50 anos e constipação deve fazer colonoscopia, independentemente de rastreio prévio ou sinais de alarme.","Falsa. A indicação segue rastreio e sinais de alarme; constipação isolada não impõe colonoscopia universal."],["D","Se medidas comportamentais falharem, bisacodil é obrigatoriamente a primeira opção medicamentosa.","Falsa. Laxativos osmóticos, especialmente polietilenoglicol, são frequentemente preferidos; estimulantes podem ser resgate ou terapia selecionada."]] },
    {"k":"lynch-vf","topic":"Câncer colorretal","d":"difícil","type":"true_false","s":"Sobre a síndrome de Lynch, julgue cada assertiva.","c":["A:V","B:F","C:V","D:F","E:V"],"g":"Lynch decorre de deficiência do reparo de incompatibilidade do DNA e associa câncer colorretal precoce, proximal e neoplasias extracolônicas.","sum":"Precoce, proximal, sincrônico/metacrônico e endométrio.","mem":"Lynch: lado direito e endométrio.","trap":"A associação ginecológica principal é endométrio, não colo uterino.","alts":[["A","A síndrome de Lynch frequentemente causa câncer colorretal antes dos 50 anos.","Verdadeira. Idade precoce é um sinal de suspeição, embora casos tardios também ocorram."],["B","Tumores colorretais sincrônicos são raros na síndrome de Lynch.","Falsa. Há risco aumentado de tumores sincrônicos e metacrônicos."],["C","O cólon direito é frequentemente acometido.","Verdadeira. Tumores proximais são característicos."],["D","Lynch II se associa principalmente a câncer do colo do útero.","Falsa. A associação ginecológica clássica é carcinoma do endométrio, além de ovário."],["E","Colectomia ampliada com anastomose ileorretal pode ser considerada após diagnóstico de câncer, ponderando função, idade e vigilância.","Verdadeira. O risco metacrônico favorece ressecção estendida em pacientes selecionados; a decisão é individualizada."]] },
    {"k":"diverticular-vf","topic":"Doença diverticular","d":"fácil","type":"true_false","s":"Sobre diverticulose e diverticulite, julgue cada assertiva.","c":["A:V","B:V","C:V","D:V"],"g":"Diverticulose descreve divertículos; doença diverticular, manifestações atribuíveis; diverticulite, inflamação com ou sem complicações.","sum":"Diverticulite complicada inclui abscesso, fístula, obstrução ou perfuração.","mem":"-ose existe; doença dá sintomas; -ite inflama.","trap":"Não confunda diverticulose assintomática com diverticulite.","alts":[["A","Diverticulose colônica é a presença de divertículos sem inflamação associada.","Verdadeira. É uma descrição anatômica."],["B","Doença diverticular é um termo abrangente para manifestações clinicamente significativas associadas a divertículos.","Verdadeira. Engloba apresentações sintomáticas e complicações."],["C","Diverticulite aguda envolve inflamação de divertículo e pode evoluir com perfuração e peritonite.","Verdadeira. Perfuração pode ser localizada ou livre."],["D","Diverticulite complicada associa abscesso, perfuração, fístula ou obstrução; na não complicada há inflamação local sem essas complicações.","Verdadeira. Essa distinção orienta prognóstico e manejo."]] },
    {"k":"crc-vf","topic":"Câncer colorretal","d":"médio","type":"true_false","s":"Sobre câncer colorretal, julgue cada assertiva.","c":["A:V","B:V","C:F","D:V","E:F"],"g":"Risco varia com histologia de adenomas e duração/extensão da colite; tumores proximais e distais têm apresentações diferentes e metástases hepáticas selecionadas podem ser tratadas com intenção curativa.","sum":"Viloso arrisca; cólon direito sangra; reto localmente avançado recebe neoadjuvância; fígado pode ser ressecável.","mem":"Direito: anemia; esquerdo: obstrução.","trap":"Metástase não significa automaticamente ausência de possibilidade curativa.","alts":[["A","Entre adenomas colorretais, componente viloso associa maior potencial de malignização que o tubular, especialmente com maior tamanho e displasia.","Verdadeira. Histologia vilosa integra critérios de adenoma avançado."],["B","Colite ulcerativa extensa e de longa duração aumenta o risco de câncer colorretal.","Verdadeira. O risco cresce com duração, extensão e atividade inflamatória."],["C","Câncer de cólon direito frequentemente se apresenta primeiro com obstrução.","Falsa. O lúmen mais amplo favorece apresentação com sangramento oculto e anemia; obstrução é mais típica à esquerda."],["D","Tumor de reto localmente avançado costuma exigir estratégia neoadjuvante ou terapia total neoadjuvante antes da cirurgia.","Verdadeira. O tratamento depende do estadiamento por imagem e de discussão multidisciplinar."],["E","Metástase hepática sempre elimina a possibilidade de tratamento curativo.","Falsa. Metástases hepáticas ressecáveis ou convertidas à ressecabilidade podem ser tratadas com intenção curativa."]] },
    {"k":"dii-histologia-vf","topic":"Doenças inflamatórias intestinais","d":"médio","type":"true_false","s":"Sobre achados endoscópicos e histológicos das doenças inflamatórias intestinais, julgue cada assertiva.","c":["A:V","B:F","C:F","D:F","E:F"],"g":"RCU é contínua a partir do reto e limitada principalmente à mucosa; Crohn é segmentar e transmural.","sum":"RCU contínua e mucosa; Crohn salteado, transmural, aftas e fístulas.","mem":"Crohn atravessa a parede.","trap":"Pseudopólipos são ilhas de mucosa regenerativa entre áreas ulceradas, não úlceras projetadas.","alts":[["A","Na RCU leve, a mucosa pode ser eritematosa e granular; em doença intensa, pode tornar-se hemorrágica, edemaciada e ulcerada.","Verdadeira. A gravidade endoscópica acompanha friabilidade, sangramento e ulceração."],["B","A RCU começa no reto, mas tipicamente deixa áreas de mucosa normal entremeadas.","Falsa. O comprometimento clássico é contínuo, sem skip lesions."],["C","Pseudopólipos da RCU são úlceras profundas que se projetam sobre mucosa normal.","Falsa. São ilhas de mucosa residual ou regenerativa entre áreas ulceradas."],["D","Crohn limita-se à mucosa e submucosa superficial, preservando as camadas profundas.","Falsa. A inflamação de Crohn é transmural."],["E","Úlceras aftoides salteadas do retossigmoide constituem a apresentação clássica inicial da RCU.","Falsa. Lesões aftoides e distribuição salteada favorecem Crohn."]] },
    {"k":"dii-conceitos-vf","topic":"Doenças inflamatórias intestinais","d":"fácil","type":"true_false","s":"Compare doença de Crohn e retocolite ulcerativa.","c":["A:F","B:V","C:V","D:F"],"g":"As duas doenças podem ter manifestações extraintestinais, mas diferem em profundidade, distribuição e histologia.","sum":"Crohn transmural; RCU mucosa, contínua e uniforme.","mem":"C de Crohn = camadas completas.","trap":"Granulomas de Crohn são não caseosos e não são obrigatórios.","alts":[["A","Crohn envolve apenas a mucosa, enquanto RCU é transmural.","Falsa. A relação está invertida: Crohn é transmural e RCU predomina na mucosa."],["B","Manifestações extraintestinais podem ocorrer nas duas doenças.","Verdadeira. Articulares, cutâneas, oculares e hepatobiliares podem ocorrer."],["C","A RCU tem distribuição tipicamente contínua e uniforme a partir do reto.","Verdadeira. A extensão proximal é contínua na apresentação clássica."],["D","Abscessos de cripta e granulomas caseosos são, respectivamente, os achados mais marcantes de RCU e Crohn.","Falsa. Abscessos de cripta podem ocorrer na RCU, mas granulomas de Crohn são não caseosos e têm baixa sensibilidade."]] },
    {"k":"pc-etiologia","topic":"Pancreatite crônica","d":"fácil","type":"single","s":"Qual é a principal etiologia de pancreatite crônica em adultos no contexto clássico das provas apresentadas?","c":["B"],"g":"O consumo crônico de álcool é uma das principais etiologias de pancreatite crônica em adultos; tabagismo é fator independente e frequentemente associado.","sum":"Álcool e tabaco são causas/fatores centrais, mas a etiologia deve ser individualizada.","mem":"Crônica clássica: álcool; aguda clássica: cálculo.","trap":"Colelitíase é causa predominante de pancreatite aguda, não de pancreatite crônica.","alts":[["A","Cálculos biliares","Incorreta. Cálculos são causa importante de pancreatite aguda."],["B","Uso crônico de álcool","Correta. É etiologia clássica e relevante de pancreatite crônica em adultos."],["C","Trauma abdominal isolado","Incorreta. Pode lesar o pâncreas, mas não é a principal etiologia populacional."],["D","Apendicite prévia","Incorreta. Não é etiologia de pancreatite crônica."]] },
    {"k":"pc-esteatorreia","topic":"Pancreatite crônica","d":"fácil","type":"single","s":"Homem de 56 anos, etilista crônico, apresenta dor epigástrica recorrente, emagrecimento, esteatorreia e calcificações pancreáticas. Qual mecanismo melhor explica a esteatorreia?","c":["C"],"g":"A destruição acinar reduz a secreção de lipase e outras enzimas, causando má digestão intraluminal, sobretudo de gorduras.","sum":"Esteatorreia pancreática é insuficiência exócrina avançada.","mem":"Sem lipase, gordura sai nas fezes.","trap":"Insuficiência endócrina explica diabetes, não diretamente esteatorreia.","alts":[["A","Redução da produção de insulina pelas células beta","Incorreta. Explica diabetes pancreatogênico, não a má digestão de gordura."],["B","Acidose sistêmica causada por menor bicarbonato","Incorreta. Bicarbonato baixo contribui para inativação enzimática, mas a melhor explicação é a deficiência de enzimas exócrinas."],["C","Má digestão de gorduras por deficiência de enzimas pancreáticas exócrinas","Correta. A perda de lipase e colipase causa esteatorreia."],["D","Aumento primário da motilidade intestinal","Incorreta. Não é o mecanismo central neste contexto."],["E","Hiperprodução de bile","Incorreta. Não ocorre hiperprodução biliar causal."]] },
    {"k":"osmotic-diarrhea","topic":"Diarreia crônica","d":"fácil","type":"single","s":"Qual característica é típica da diarreia osmótica da intolerância à lactose?","c":["D"],"g":"Solutos não absorvidos retêm água; o quadro melhora com jejum e a fermentação pode reduzir o pH fecal.","sum":"Osmótica melhora no jejum.","mem":"Sem substrato, sem osmose.","trap":"Diarreia noturna persistente e sangue são sinais de doença orgânica.","alts":[["A","Persiste inalterada durante jejum prolongado","Incorreta. Isso favorece mecanismo secretor."],["B","Calprotectina fecal necessariamente muito elevada","Incorreta. Calprotectina elevada sugere inflamação intestinal."],["C","Evacuações noturnas progressivas","Incorreta. É sinal de alarme para causa orgânica."],["D","Melhora com o jejum e pode associar-se a pH fecal ácido","Correta. A retirada da lactose remove o soluto osmoticamente ativo."],["E","Sangue visível nas fezes","Incorreta. Não é manifestação típica de intolerância à lactose."]] },
    {"k":"celiac-next-step","topic":"Doença celíaca","d":"médio","type":"single","s":"Mulher de 35 anos com diarreia crônica, meteorismo, anemia e anti-transglutaminase positivo ainda consome glúten. Qual é a melhor sequência diagnóstica e terapêutica?","c":["C"],"g":"Na maioria dos adultos, confirma-se com endoscopia e múltiplas biópsias duodenais antes de iniciar dieta sem glúten permanente.","sum":"Sorologia positiva + biópsias duodenais; depois dieta sem glúten.","mem":"Biopsie enquanto ainda há glúten.","trap":"Iniciar dieta antes das biópsias pode normalizar achados e dificultar confirmação.","alts":[["A","Biópsias duodenais e reposição de enzimas pancreáticas","Incorreta. Enzimas tratam insuficiência pancreática, não doença celíaca."],["B","Biópsias duodenais e apenas restrição de lactose","Incorreta. Intolerância secundária pode ocorrer, mas não substitui dieta sem glúten."],["C","Endoscopia com múltiplas biópsias duodenais e, após confirmação, dieta isenta de glúten","Correta. É a abordagem habitual no adulto."],["D","Colonoscopia e dieta sem glúten","Incorreta. A mucosa-alvo diagnóstica está no duodeno."],["E","Colonoscopia e enzimas digestivas","Incorreta. Não confirma nem trata adequadamente a hipótese."]] },
    {"k":"uc-high-grade-dysplasia","topic":"Retocolite ulcerativa","d":"difícil","type":"single","s":"Homem de 35 anos com pancolite ulcerativa há 10 anos apresenta atividade clínica e displasia de alto grau confirmada no cólon transverso. Qual a melhor conduta?","c":["C"],"g":"Displasia de alto grau não passível de ressecção endoscópica curativa ou multifocal em colite de longa duração indica abordagem cirúrgica pelo alto risco de câncer sincrônico.","sum":"Displasia de alto grau confirmada exige avaliação cirúrgica.","mem":"HGD + colite longa = pense colectomia.","trap":"Escalonar imunossupressão não elimina o risco neoplásico já documentado.","alts":[["A","Azatioprina e reavaliação em três meses","Incorreta. Não trata o risco oncológico da displasia de alto grau."],["B","Infliximabe e vigilância semestral isolada","Incorreta. Controle inflamatório não substitui tratamento da displasia de alto grau."],["C","Programar proctocolectomia restauradora com anastomose bolsa ileal-anal, após avaliação multidisciplinar","Correta. É a operação padrão em paciente adequado com indicação oncológica."],["D","Apenas aumentar mesalazina e corticoide tópico","Incorreta. É insuficiente para pancolite ativa e não aborda displasia."],["E","Aguardar oito semanas sem revisão anatomopatológica","Incorreta. A lâmina deve ser confirmada por patologista experiente, mas simples espera não é a melhor conduta."]] },
    {"k":"crohn-ddx","topic":"Doença de Crohn","d":"médio","type":"single","s":"Mulher com dor em fossa ilíaca direita, febre, perda ponderal, anemia, PCR elevada, estenose ileal e úlceras lineares profundas tem suspeita de Crohn ileocecal. Qual opção NÃO integra adequadamente o diagnóstico diferencial estrutural desse quadro?","c":["B"],"g":"Tuberculose, linfoma e Yersinia podem simular ileíte de Crohn; SII não causa estenose, úlceras ou inflamação sistêmica.","sum":"SII é funcional e não produz lesão estrutural.","mem":"Febre + anemia + úlcera não é SII.","trap":"Um diagnóstico funcional não explica massa e estenose ileal.","alts":[["A","Doença de Crohn ileocecal","Incorreta como resposta ao EXCETO; é a principal hipótese."],["B","Síndrome do intestino irritável","Correta. Não explica achados inflamatórios e estruturais."],["C","Tuberculose intestinal","Incorreta. É diferencial importante de ileíte granulomatosa."],["D","Linfoma de intestino delgado","Incorreta. Pode causar massa, sintomas sistêmicos e estenose."],["E","Ileocolite por Yersinia","Incorreta. Pode mimetizar ileíte terminal e apendicite."]] },
    {"k":"ibs-colonoscopy","topic":"Síndrome do intestino irritável","d":"médio","type":"single","s":"Mulher de 32 anos apresenta dor abdominal recorrente aliviada após evacuação, diarreia pós-prandial e piora com estresse, sem sangue, febre, perda ponderal ou outros sinais de alarme. Assinale a alternativa incorreta.","c":["A"],"g":"Em paciente jovem com quadro típico e sem alarme, faz-se diagnóstico positivo e investigação limitada; colonoscopia não é obrigatória.","sum":"SII sem alarme não exige colonoscopia rotineira.","mem":"SII: diagnóstico positivo, não por exclusão infinita.","trap":"Rastreio etário e sinais de alarme continuam valendo.","alts":[["A","Colonoscopia está obrigatoriamente indicada apenas por esse quadro","Correta como alternativa incorreta. Não há indicação rotineira no cenário descrito."],["B","IgA total e anti-transglutaminase podem integrar a avaliação da forma diarreica","Incorreta como resposta; é conduta apropriada para excluir doença celíaca."],["C","Antiespasmódico pode ser considerado para dor","Incorreta como resposta; pode ser usado de modo individualizado."],["D","Abordagem multidisciplinar pode melhorar o controle","Incorreta como resposta; dieta, atividade e saúde mental podem ser relevantes."],["E","Terapia cognitivo-comportamental pode ser indicada","Incorreta como resposta; terapias cérebro-intestino têm evidência em pacientes selecionados."]] },
    {"k":"pc-enzyme-treatment","topic":"Pancreatite crônica","d":"médio","type":"single","s":"Homem de 60 anos, etilista e tabagista, apresenta dor epigástrica irradiada para o dorso, perda ponderal, esteatorreia, diabetes recente, calcificações pancreáticas e ascite. Assinale a alternativa correta.","c":["D"],"g":"Reposição enzimática pancreática trata insuficiência exócrina e é acompanhada por melhora de esteatorreia, peso e marcadores nutricionais.","sum":"Elastase fecal baixa sugere IEP; ascite pancreática costuma ter GASA baixo e amilase alta.","mem":"Enzima melhora fezes e peso.","trap":"GLP-1 não é automaticamente a primeira escolha no diabetes tipo 3c.","alts":[["A","Na insuficiência exócrina, espera-se elastase fecal acima de 200 µg/g","Incorreta. Valores abaixo de 200 µg/g sugerem insuficiência; abaixo de 100 favorecem forma grave."],["B","Morfina é sempre a primeira escolha para dor crônica","Incorreta. O manejo é escalonado e opioides não são primeira escolha rotineira."],["C","Na ascite pancreática, espera-se GASA acima de 1,1 g/dL","Incorreta. É tipicamente exsudativa, com GASA baixo e amilase elevada."],["D","Enzimas pancreáticas são indicadas, e resposta pode ser avaliada por ganho ponderal e redução da esteatorreia","Correta. São desfechos clínicos fundamentais."],["E","Análogo de GLP-1 é obrigatoriamente o tratamento inicial do diabetes tipo 3c","Incorreta. O tratamento é individualizado; insulina é frequentemente necessária e segurança pancreática deve ser considerada."]] },
    {"k":"acute-abdomen-appendicitis","topic":"Abdome agudo","d":"fácil","type":"single","s":"Mulher de 25 anos apresenta dor em fossa ilíaca direita, febre, náuseas e sinal de Blumberg. Qual o tipo de abdome agudo e o exame de imagem mais apropriado entre as opções?","c":["D"],"g":"Apendicite é abdome agudo inflamatório; em adulto não gestante, TC tem elevada acurácia.","sum":"FID + febre + Blumberg = apendicite até prova em contrário.","mem":"Inflamação confirma com TC no adulto.","trap":"Ultrassom pode ser preferido em gestantes e crianças, conforme o contexto.","alts":[["A","Perfurativo; endoscopia alta","Incorreta. O quadro localiza-se em FID e endoscopia não confirma apendicite."],["B","Vascular; angiotomografia","Incorreta. Não há padrão de isquemia mesentérica."],["C","Obstrutivo; radiografia em pé","Incorreta. Não há síndrome obstrutiva."],["D","Inflamatório; tomografia de abdome","Correta. É a combinação compatível com apendicite em adulta."],["E","Hemorrágico; ultrassonografia transvaginal","Incorreta. O caso não descreve instabilidade ou sangramento."]] },
    {"k":"acute-abdomen-obstruction","topic":"Abdome agudo","d":"fácil","type":"single","s":"Homem de 70 anos com hérnia inguinal apresenta dor difusa, distensão, vômitos biliosos e parada de fezes e flatos há 48 horas. Qual síndrome e exame inicial melhor se ajustam ao caso entre as opções?","c":["C"],"g":"O quadro é de obstrução intestinal mecânica; radiografia pode ser exame inicial, embora TC seja frequentemente necessária para causa e complicações.","sum":"Distensão + vômito + obstipação = obstrução.","mem":"Obstrução desenha níveis hidroaéreos.","trap":"Sinais de estrangulamento exigem TC e cirurgia urgente, sem atrasos.","alts":[["A","Inflamatório; ultrassonografia","Incorreta. O conjunto é obstrutivo."],["B","Perfurativo; TC com contraste","Incorreta. Não há pneumoperitônio ou peritonite descritos."],["C","Obstrutivo; radiografia de abdome em ortostase","Correta entre as opções. Pode demonstrar alças dilatadas e níveis hidroaéreos."],["D","Hemorrágico; ressonância","Incorreta. Não há evidência de hemorragia."],["E","Vascular; Doppler de membros inferiores","Incorreta. O exame não avalia a causa abdominal descrita."]] },
    {"k":"pancreas-neoadjuvant","topic":"Câncer de pâncreas","d":"médio","type":"single","s":"Quanto à quimioterapia neoadjuvante no adenocarcinoma pancreático, assinale a alternativa correta.","c":["C"],"g":"Terapia neoadjuvante é particularmente considerada em doença borderline ressecável e localmente avançada selecionada, buscando controle sistêmico e ressecção R0.","sum":"Borderline: neoadjuvância antes de decidir a ressecção.","mem":"Vaso encostado, trate antes.","trap":"A estratégia para tumor claramente ressecável varia e não torna neoadjuvância universal.","alts":[["A","É indicada apenas em doença metastática","Incorreta. Doença metastática recebe terapia sistêmica paliativa, não neoadjuvância com cirurgia planejada."],["B","É reservada a tumores já ressecados com margens livres","Incorreta. Isso descreve contexto adjuvante."],["C","Deve ser considerada em tumor borderline ressecável ou com envolvimento vascular selecionado","Correta. É cenário clássico para abordagem neoadjuvante."],["D","É obrigatória antes de toda cirurgia, qualquer que seja o estágio","Incorreta. A decisão depende de ressecabilidade, biologia e equipe multidisciplinar."],["E","Nunca oferece benefício clínico","Incorreta. Pode selecionar pacientes e aumentar chance de ressecção R0 em cenários apropriados."]] }
  ]$data$::jsonb) AS x(k text,topic text,d text,type text,s text,c jsonb,g text,sum text,mem text,trap text,alts jsonb)
  LOOP
    SELECT id INTO v_topic_id FROM public.topics
    WHERE discipline_id=v_discipline_id AND name=q.topic LIMIT 1;
    IF v_topic_id IS NULL THEN
      v_topic_id:=pg_temp.gastro_p3_uuid('gastro-topic-'||q.topic);
      INSERT INTO public.topics(id,discipline_id,name)
      VALUES(v_topic_id,v_discipline_id,q.topic)
      ON CONFLICT(id) DO UPDATE SET name=EXCLUDED.name;
    END IF;

    v_question_id:=pg_temp.gastro_p3_uuid('gastro-p3-'||q.k);
    INSERT INTO public.questions(
      id,discipline_id,topic_id,exam,difficulty,statement,question_type,
      correct_answer,correct_answers,general_comment,summary,memory_tip,trap,
      reference,active,image_url
    ) VALUES(
      v_question_id,v_discipline_id,v_topic_id,'P3',q.d,q.s,q.type,
      q.c->>0,ARRAY(SELECT jsonb_array_elements_text(q.c)),q.g,q.sum,q.mem,q.trap,
      'Prova 3 de Gastroenterologia — payload deduplicado e revisado em 2026.',true,NULL
    ) ON CONFLICT(id) DO UPDATE SET
      topic_id=EXCLUDED.topic_id,exam='P3',difficulty=EXCLUDED.difficulty,
      statement=EXCLUDED.statement,question_type=EXCLUDED.question_type,
      correct_answer=EXCLUDED.correct_answer,correct_answers=EXCLUDED.correct_answers,
      general_comment=EXCLUDED.general_comment,summary=EXCLUDED.summary,
      memory_tip=EXCLUDED.memory_tip,trap=EXCLUDED.trap,reference=EXCLUDED.reference,
      active=true,image_url=NULL;

    DELETE FROM public.alternatives WHERE question_id=v_question_id;
    FOR a IN SELECT value FROM jsonb_array_elements(q.alts)
    LOOP
      INSERT INTO public.alternatives(id,question_id,letter,text,explanation)
      VALUES(pg_temp.gastro_p3_uuid(v_question_id::text||(a->>0)),v_question_id,a->>0,a->>1,a->>2);
    END LOOP;
  END LOOP;
END $$;

DO $$
DECLARE
  v_questions integer;
  v_true_false integer;
  v_blank integer;
  v_bad_tf integer;
BEGIN
  SELECT count(*),count(*) FILTER(WHERE question_type='true_false')
    INTO v_questions,v_true_false
  FROM public.questions
  WHERE reference='Prova 3 de Gastroenterologia — payload deduplicado e revisado em 2026.' AND active;

  SELECT count(*) INTO v_blank
  FROM public.alternatives a JOIN public.questions q ON q.id=a.question_id
  WHERE q.reference='Prova 3 de Gastroenterologia — payload deduplicado e revisado em 2026.'
    AND (coalesce(trim(a.text),'')='' OR coalesce(trim(a.explanation),'')='');

  SELECT count(*) INTO v_bad_tf FROM public.questions q
  WHERE q.reference='Prova 3 de Gastroenterologia — payload deduplicado e revisado em 2026.'
    AND q.question_type='true_false'
    AND cardinality(q.correct_answers)<>(SELECT count(*) FROM public.alternatives a WHERE a.question_id=q.id);

  IF v_questions<>20 OR v_true_false<>9 OR v_blank<>0 OR v_bad_tf<>0 THEN
    RAISE EXCEPTION 'Auditoria Gastro P3 falhou: questões=%, V/F=%, vazias=%, V/F incompletas=%',
      v_questions,v_true_false,v_blank,v_bad_tf;
  END IF;
END $$;

COMMIT;
